*** Settings ***

Documentation  This file will only store variables for homepage.

*** Variables ***

${MY_homeURL}  https://iprice.my/
${VN_homeURL}  https://iprice.vn/
${ID_homeURL}  https://iprice.co.id/
${SG_homeURL}  https://iprice.sg/
${PH_homeURL}  https://iprice.ph/
${HK_homeURL}  https://iprice.hk/
${TH_homeURL}  https://ipricethailand.com/

${MY_homeTitle}  Online Shopping, Coupons & Discount Codes at iPrice Malaysia
${ID_homeTitle}  Belanja Online, Kode Kupon & Diskon di iPrice Indonesia
${VN_homeTitle}  Shopping trực tuyến, Mã coupon & khuyến mãi tại iPrice Việt Nam
${SG_homeTitle}  Online Shopping, Coupons & Discount Codes at iPrice Singapore
${PH_homeTitle}  Online Shopping, Coupons & Discount Codes at iPrice Philippines
${HK_homeTitle}  Online Shopping, Coupons & Discount Codes at iPrice Hong Kong
${TH_homeTitle}  iPriceThailand - ค้นหา เช็กราคา ที่เดียวครบสุดคุ้ม

${MY_courtesy_products}  //div[@id='courtesies-banner']//a[@href='https://iprice.my/']//span[text()='Products']
${VN_courtesy_products}  //div[@id='courtesies-banner']//a[@href='https://iprice.vn/']//span[text()='Sản phẩm']
${ID_courtesy_products}  //div[@id='courtesies-banner']//a[@href='https://iprice.co.id/']//span[text()='Produk']
${SG_courtesy_products}  //div[@id='courtesies-banner']//a[@href='https://iprice.sg/']//span[text()='Products']
${PH_courtesy_products}  //div[@id='courtesies-banner']//a[@href='https://iprice.ph/']//span[text()='Products']
${HK_courtesy_products}  //div[@id='courtesies-banner']//a[@href='https://iprice.hk/']//span[text()='Products']
${TH_courtesy_products}  //div[@id='courtesies-banner']//a[@href='https://ipricethailand.com/']//span[text()='สินค้า']

${EN_courtesy_products_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Products']
${VN_courtesy_products_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Sản phẩm']
${ID_courtesy_products_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Produk']
${TH_courtesy_products_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='สินค้า']

${MY_courtesy_coupons}  //div[@id='courtesies-banner']//a[@href='https://iprice.my/coupons/']//span[text()='Coupons']
${VN_courtesy_coupons}  //div[@id='courtesies-banner']//a[@href='https://iprice.vn/coupons/']//span[text()='Mã giảm giá']
${ID_courtesy_coupons}  //div[@id='courtesies-banner']//a[@href='https://iprice.co.id/coupons/']//span[text()='Kupon']
${SG_courtesy_coupons}  //div[@id='courtesies-banner']//a[@href='https://iprice.sg/coupons/']//span[text()='Coupons']
${PH_courtesy_coupons}  //div[@id='courtesies-banner']//a[@href='https://iprice.ph/coupons/']//span[text()='Coupons']
${HK_courtesy_coupons}  //div[@id='courtesies-banner']//a[@href='https://iprice.hk/coupons/']//span[text()='Coupons']
${TH_courtesy_coupons}  //div[@id='courtesies-banner']//a[@href='https://ipricethailand.com/coupons/']//span[text()='คูปอง']

${EN_courtesy_coupons_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Coupons']
${VN_courtesy_coupons_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Mã giảm giá']
${ID_courtesy_coupons_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Kupon']
${TH_courtesy_coupons_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='คูปอง']

${MY_courtesy_trends}  //div[@id='courtesies-banner']//a[@href='https://iprice.my/trends/']//span[text()='Trends']
${VN_courtesy_trends}  //div[@id='courtesies-banner']//a[@href='https://iprice.vn/xu-huong/']//span[text()='Xu hướng']
${ID_courtesy_trends}  //div[@id='courtesies-banner']//a[@href='https://iprice.co.id/trend/']//span[text()='Trend']
${SG_courtesy_trends}  //div[@id='courtesies-banner']//a[@href='https://iprice.sg/trends/']//span[text()='Trends']
${PH_courtesy_trends}  //div[@id='courtesies-banner']//a[@href='https://iprice.ph/trends/']//span[text()='Trends']
${HK_courtesy_trends}  //div[@id='courtesies-banner']//a[@href='https://iprice.hk/trends/']//span[text()='Trends']
${TH_courtesy_trends}  //div[@id='courtesies-banner']//a[@href='https://ipricethailand.com/%E0%B9%80%E0%B8%97%E0%B8%A3%E0%B8%99%E0%B8%94/']//span[text()='เทรนด์']

${EN_courtesy_trends_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Trends']
${VN_courtesy_trends_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Xu hướng']
${ID_courtesy_trends_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='Trend']
${TH_courtesy_trends_highlight}  //div[@id='courtesies-banner']//a[@class='flex-1 flex-none-l text-align-center active']//span[text()='เทรนด์']

${MY_header_logo_link}  //div[@id='banner']//a[contains(@class,'logo h2') and @href='https://iprice.my/']
${VN_header_logo_link}  //div[@id='banner']//a[contains(@class,'logo h2') and @href='https://iprice.vn/']
${ID_header_logo_link}  //div[@id='banner']//a[contains(@class,'logo h2') and @href='https://iprice.co.id/']
${SG_header_logo_link}  //div[@id='banner']//a[contains(@class,'logo h2') and @href='https://iprice.sg/']
${PH_header_logo_link}  //div[@id='banner']//a[contains(@class,'logo h2') and @href='https://iprice.ph/']
${HK_header_logo_link}  //div[@id='banner']//a[contains(@class,'logo h2') and @href='https://iprice.hk/']
${TH_header_logo_link}  //div[@id='banner']//a[contains(@class,'logo h2') and @href='https://ipricethailand.com/']

${EN_header_search_compare_save}  //div[@id='banner']//span[normalize-space(text()='Search, Compare & Save')]
${VN_header_search_compare_save}  //div[@id='banner']//span[normalize-space(text()='Tìm kiếm, So sánh & Tiết kiệm')]
${ID_header_search_compare_save}  //div[@id='banner']//span[normalize-space(text()='Cari, Bandingkan & Lebih Hemat')]
${TH_header_search_compare_save}  //div[@id='banner']//span[normalize-space(text()='ค้นหา เช็คราคา ที่เดียวครบสุดคุ้ม')]

${MY_header_search_input}  //div[@id='banner']//input[@placeholder='Search for products, coupons or brands...']
${VN_header_search_input}  //div[@id='banner']//input[@placeholder='Tìm kiếm sản phẩm, coupon hoặc thương hiệu...']
${ID_header_search_input}  //div[@id='banner']//input[@placeholder='Cari produk, kupon atau brand...']
${SG_header_search_input}  //div[@id='banner']//input[@placeholder='Search for products, coupons or brands...']
${PH_header_search_input}  //div[@id='banner']//input[@placeholder='Search for products, coupons or brands...']
${HK_header_search_input}  //div[@id='banner']//input[@placeholder='Search for products, coupons or brands...']
${TH_header_search_input}  //div[@id='banner']//input[@placeholder='ค้นหาสินค้า,คูปองหรือแบรนด์...']
${header_search_icon}  //div[@id='banner']//i[@class='icon icon-search-blue']

${products_mega_menu_electronics_icon}  //div[@id='mega-menu']//i[@class='icon-electronics none']
${products_mega_menu_fashion_icon}  //div[@id='mega-menu']//i[@class='icon-fashion none']
${products_mega_menu_sports_outdoors_icon}  //div[@id='mega-menu']//i[@class='icon-sports-outdoor none']
${products_mega_menu_home_living_icon}  //div[@id='mega-menu']//i[@class='icon-home-living none']
${products_mega_menu_kid_toys_icon}  //div[@id='mega-menu']//i[@class='icon-kids-toys none']
${products_mega_menu_health_beauty_icon}  //div[@id='mega-menu']//i[@class='icon-health-beauty none']
${products_mega_menu_automotive_icon}  //div[@id='mega-menu']//i[@class='icon-automotive none']
${EN_products_mega_menu_electronics}  //div[@id='mega-menu']//strong[normalize-space()='Electronics']
${VN_products_mega_menu_electronics}  //div[@id='mega-menu']//strong[normalize-space()='Điện máy']
${ID_products_mega_menu_electronics}  //div[@id='mega-menu']//strong[normalize-space()='Elektronik']
${TH_products_mega_menu_electronics}  //div[@id='mega-menu']//strong[normalize-space()='อิเล็กทรอนิกส์']
${EN_products_mega_menu_fashion}  //div[@id='mega-menu']//strong[normalize-space()='Fashion']
${VN_products_mega_menu_fashion}  //div[@id='mega-menu']//strong[normalize-space()='Thời trang']
${ID_products_mega_menu_fashion}  //div[@id='mega-menu']//strong[normalize-space()='Fashion']
${TH_products_mega_menu_fashion}  //div[@id='mega-menu']//strong[normalize-space()='แฟชั่น']
${EN_products_mega_menu_sports_outdoors}  //div[@id='mega-menu']//strong[normalize-space()='Sports & Outdoors']
${VN_products_mega_menu_sports_outdoors}  //div[@id='mega-menu']//strong[normalize-space()='Thể thao & Dã ngoại']
${ID_products_mega_menu_sports_outdoors}  //div[@id='mega-menu']//strong[normalize-space()='Outdoor']
${TH_products_mega_menu_sports_outdoors}  //div[@id='mega-menu']//strong[normalize-space()='กีฬาและกิจกรรมกลางแจ้ง']
${EN_products_mega_menu_home_living}  //div[@id='mega-menu']//strong[normalize-space()='Home & Living']
${VN_products_mega_menu_home_living}  //div[@id='mega-menu']//strong[normalize-space()='Đồ gia dụng']
${ID_products_mega_menu_home_living}  //div[@id='mega-menu']//strong[normalize-space()='Rumah Tangga']
${TH_products_mega_menu_home_living}  //div[@id='mega-menu']//strong[normalize-space()='บ้านและการตกแต่ง']
${EN_products_mega_menu_kids_toys}  //div[@id='mega-menu']//strong[normalize-space()='Kids & Toys']
${VN_products_mega_menu_kids_toys}  //div[@id='mega-menu']//strong[normalize-space()='Đồ trẻ em']
${ID_products_mega_menu_kids_toys}  //div[@id='mega-menu']//strong[normalize-space()='Mainan & Anak']
${TH_products_mega_menu_kids_toys}  //div[@id='mega-menu']//strong[normalize-space()='แม่และเด็ก']
${EN_products_mega_menu_health_beauty}  //div[@id='mega-menu']//strong[normalize-space()='Health & Beauty']
${VN_products_mega_menu_health_beauty}  //div[@id='mega-menu']//strong[normalize-space()='Sức khỏe & Làm đẹp']
${ID_products_mega_menu_health_beauty}  //div[@id='mega-menu']//strong[normalize-space()='Kesehatan']
${TH_products_mega_menu_health_beauty}  //div[@id='mega-menu']//strong[normalize-space()='สุขภาพและความงาม']
${EN_products_mega_menu_automotive}  //div[@id='mega-menu']//strong[normalize-space()='Automotive']
${VN_products_mega_menu_automotive}  //div[@id='mega-menu']//strong[normalize-space()='Ô tô, xe máy']
${ID_products_mega_menu_automotive}  //div[@id='mega-menu']//strong[normalize-space()='Otomotif']
${TH_products_mega_menu_automotive}  //div[@id='mega-menu']//strong[normalize-space()='ยานยนต์']

${products_banner}  //div[@id="carousel-banners-amp"]

${homepage_bottom_product_images}  //img[contains(@class,'lazy product-img')]

# ${MY_header_coupon_logo_link_and_text}  //div[@id='news-button']//a[@href='https://iprice.my/coupons/']//button[normalize-space(text())='Coupons & Offers']
# ${VN_header_coupon_logo_link_and_text}  //div[@id='news-button']//a[@href='https://iprice.vn/coupons/']//button[normalize-space(text())='Coupon & Ưu đãi']
# ${ID_header_coupon_logo_link_and_text}  //div[@id='news-button']//a[@href='https://iprice.co.id/coupons/']//button[normalize-space(text())='Kupon & Penawaran']
# ${SG_header_coupon_logo_link_and_text}  //div[@id='news-button']//a[@href='https://iprice.sg/coupons/']//button[normalize-space(text())='Coupons & Offers']
# ${PH_header_coupon_logo_link_and_text}  //div[@id='news-button']//a[@href='https://iprice.ph/coupons/']//button[normalize-space(text())='Coupons & Offers']
# ${HK_header_coupon_logo_link_and_text}  //div[@id='news-button']//a[@href='https://iprice.hk/coupons/']//button[normalize-space(text())='Coupons & Offers']
# ${TH_header_coupon_logo_link_and_text}  //div[@id='news-button']//a[@href='https://ipricethailand.com/coupons/']//*[(contains(text(),'คูปอง &') and (normalize-space(text()='ข้อเสนอ')))]

# ${MY_header_categories_clothing_link_text}  //div[@id='menu']//a[@href='https://iprice.my/clothing/']//span[text()='Clothing']
# ${VN_header_categories_clothing_link_text}  //div[@id='menu']//a[@href='https://iprice.vn/quan-ao/']//span[text()='Quần áo']
# ${ID_header_categories_clothing_link_text}  //div[@id='menu']//a[@href='https://iprice.co.id/pakaian/']//span[text()='Pakaian']
# ${SG_header_categories_clothing_link_text}  //div[@id='menu']//a[@href='https://iprice.sg/clothing/']//span[text()='Clothing']
# ${PH_header_categories_clothing_link_text}  //div[@id='menu']//a[@href='https://iprice.ph/clothing/']//span[text()='Clothing']
# ${HK_header_categories_clothing_link_text}  //div[@id='menu']//a[@href='https://iprice.hk/clothing/']//span[text()='Clothing']
# ${TH_header_categories_clothing_link_text}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองแตงกาย/']//span[text()='เครื่องแต่งกาย']

# ${MY_header_categories_shoes_link_text}  //div[@id='menu']//a[@href='https://iprice.my/shoes/']//span[text()='Shoes']
# ${VN_header_categories_shoes_link_text}  //div[@id='menu']//a[@href='https://iprice.vn/giay-dep/']//span[text()='Giày dép']
# ${ID_header_categories_shoes_link_text}  //div[@id='menu']//a[@href='https://iprice.co.id/sepatu/']//span[text()='Sepatu']
# ${SG_header_categories_shoes_link_text}  //div[@id='menu']//a[@href='https://iprice.sg/shoes/']//span[text()='Shoes']
# ${PH_header_categories_shoes_link_text}  //div[@id='menu']//a[@href='https://iprice.ph/shoes/']//span[text()='Shoes']
# ${HK_header_categories_shoes_link_text}  //div[@id='menu']//a[@href='https://iprice.hk/shoes/']//span[text()='Shoes']
# ${TH_header_categories_shoes_link_text}  //div[@id='menu']//a[@href='https://ipricethailand.com/รองเทา/']//span[text()='รองเท้า']

${EN_products_header_categories_electronics}  //div[@id='mega-menu']//div[@data-target='electronics']//strong[normalize-space(text()='Electronics')]
${VN_products_header_categories_electronics}  //div[@id='mega-menu']//div[@data-target='electronics']//strong[normalize-space(text()='Điện máy')]
${ID_products_header_categories_electronics}  //div[@id='mega-menu']//div[@data-target='electronics']//strong[normalize-space(text()='Elektronik')]
${TH_products_header_categories_electronics}  //div[@id='mega-menu']//div[@data-target='electronics']//strong[normalize-space(text()='อิเล็กทรอนิกส์')]

${search_compare_save_electronic_gaming_box}  //div[@id='hp-electronics']
${search_compare_save_fashion_beauty_box}  //div[@id='hp-fashion']
${search_compare_save_coupons_offers_box}  //div[@id='hp-coupon']

${EN_search_compare_save_electronic_gaming_box_computing}  //div[@id='hp-parent']//span[text()='Computing']
${VN_search_compare_save_electronic_gaming_box_computing}  //div[@id='hp-parent']//span[text()='Tin học']
${ID_search_compare_save_electronic_gaming_box_computing}  //div[@id='hp-parent']//span[text()='Komputer']
${TH_search_compare_save_electronic_gaming_box_computing}  //div[@id='hp-parent']//span[text()='อุปกรณ์คอมพิวเตอร์']
${EN_search_compare_save_electronic_gaming_box_phone_tablet}  //div[@id='hp-parent']//span[text()='Phones & Tablets']
${VN_search_compare_save_electronic_gaming_box_phone_tablet}  //div[@id='hp-parent']//span[text()='Điện thoại & Máy tính bảng']
${ID_search_compare_save_electronic_gaming_box_phone_tablet}  //div[@id='hp-parent']//span[text()='Ponsel & Tablet']
${TH_search_compare_save_electronic_gaming_box_phone_tablet}  //div[@id='hp-parent']//span[text()='โทรศัพท์และแท็บเล็ต']
${EN_search_compare_save_electronic_gaming_box_gaming}  //div[@id='hp-parent']//span[text()='Gaming']
${VN_search_compare_save_electronic_gaming_box_gaming}  //div[@id='hp-parent']//span[text()='Chơi game']
${ID_search_compare_save_electronic_gaming_box_gaming}  //div[@id='hp-parent']//span[text()='Video Game']
${TH_search_compare_save_electronic_gaming_box_gaming}  //div[@id='hp-parent']//span[text()='เครื่องเล่นเกมส์']
${EN_search_compare_save_electronic_gaming_box_camera_photo}  //div[@id='hp-parent']//span[text()='Camera & Photo']
${VN_search_compare_save_electronic_gaming_box_camera_photo}  //div[@id='hp-parent']//span[text()='Máy ảnh']
${ID_search_compare_save_electronic_gaming_box_camera_photo}  //div[@id='hp-parent']//span[text()='Kamera & Foto']
${TH_search_compare_save_electronic_gaming_box_camera_photo}  //div[@id='hp-parent']//span[text()='กล้องถ่ายรูปและรูปภาพ']
${EN_search_compare_save_electronic_gaming_box_tv_video_dvd}  //div[@id='hp-parent']//span[text()='TV, Video & DVD']
${VN_search_compare_save_electronic_gaming_box_tv_video_dvd}  //div[@id='hp-parent']//span[text()='TV, Video & DVD']
${ID_search_compare_save_electronic_gaming_box_tv_video_dvd}  //div[@id='hp-parent']//span[text()='TV, Video & DVD']
${TH_search_compare_save_electronic_gaming_box_tv_video_dvd}  //div[@id='hp-parent']//span[text()='ทีวี วีดีโอ และดีวีดี']
${EN_search_compare_save_electronic_gaming_box_appliances}  //div[@id='hp-parent']//span[text()='Appliances']
${VN_search_compare_save_electronic_gaming_box_appliances}  //div[@id='hp-parent']//span[text()='Đồ gia dụng']
${ID_search_compare_save_electronic_gaming_box_appliances}  //div[@id='hp-parent']//span[text()='Peralatan']
${TH_search_compare_save_electronic_gaming_box_appliances}  //div[@id='hp-parent']//span[text()='เครื่องใช้ไฟฟ้า']
${EN_search_compare_save_electronic_gaming_box_see_all_categories}  //div[@id='hp-parent']//div[@id='tech']//span[text()='See all categories ❯']
${VN_search_compare_save_electronic_gaming_box_see_all_categories}  //div[@id='hp-parent']//div[@id='tech']//span[text()='Xem tất cả danh mục ❯']
${ID_search_compare_save_electronic_gaming_box_see_all_categories}  //div[@id='hp-parent']//div[@id='tech']//span[text()='Lihat semua kategori ❯']
${TH_search_compare_save_electronic_gaming_box_see_all_categories}  //div[@id='hp-parent']//div[@id='tech']//span[text()='เลือกดูหมวดหมู่ทั้งหมด ❯']
${EN_search_compare_save_electronic_gaming_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='tech']//span[text()='Shop by brands ❯']
${VN_search_compare_save_electronic_gaming_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='tech']//span[text()='Chọn mua theo Thương Hiệu ❯']
${ID_search_compare_save_electronic_gaming_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='tech']//span[text()='Belanja berdasarkan Merek ❯']
${TH_search_compare_save_electronic_gaming_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='tech']//span[text()='เลือกซื้อจากแบรนด์ ❯']

${EN_search_compare_save_fashion_beauty_box_clothing}  //div[@id='hp-parent']//span[text()='Clothing']
${VN_search_compare_save_fashion_beauty_box_clothing}  //div[@id='hp-parent']//span[text()='Quần áo']
${ID_search_compare_save_fashion_beauty_box_clothing}  //div[@id='hp-parent']//span[text()='Pakaian']
${TH_search_compare_save_fashion_beauty_box_clothing}  //div[@id='hp-parent']//span[text()='เครื่องแต่งกาย']
${EN_search_compare_save_fashion_beauty_box_shoes}  //div[@id='hp-parent']//span[text()='Shoes']
${VN_search_compare_save_fashion_beauty_box_shoes}  //div[@id='hp-parent']//span[text()='Giày dép']
${ID_search_compare_save_fashion_beauty_box_shoes}  //div[@id='hp-parent']//span[text()='Sepatu']
${TH_search_compare_save_fashion_beauty_box_shoes}  //div[@id='hp-parent']//span[text()='รองเท้า']
${EN_search_compare_save_fashion_beauty_box_bags}  //div[@id='hp-parent']//span[text()='Bags']
${VN_search_compare_save_fashion_beauty_box_bags}  //div[@id='hp-parent']//span[text()='Túi']
${ID_search_compare_save_fashion_beauty_box_bags}  //div[@id='hp-parent']//span[text()='Tas']
${TH_search_compare_save_fashion_beauty_box_bags}  //div[@id='hp-parent']//span[text()='กระเป๋า']
${EN_search_compare_save_fashion_beauty_box_health_beauty}  //div[@id='hp-parent']//span[text()='Health & Beauty']
${VN_search_compare_save_fashion_beauty_box_health_beauty}  //div[@id='hp-parent']//span[text()='Sức khoẻ&Làm đẹp']
${ID_search_compare_save_fashion_beauty_box_health_beauty}  //div[@id='hp-parent']//span[text()='Kesehatan & Kecantikan']
${TH_search_compare_save_fashion_beauty_box_health_beauty}  //div[@id='hp-parent']//span[text()='สุขภาพและความงาม']
${EN_search_compare_save_fashion_beauty_box_jewellery}  //div[@id='hp-parent']//span[text()='Jewellery']
${VN_search_compare_save_fashion_beauty_box_jewellery}  //div[@id='hp-parent']//span[text()='Trang sức']
${ID_search_compare_save_fashion_beauty_box_jewellery}  //div[@id='hp-parent']//span[text()='Perhiasan']
${TH_search_compare_save_fashion_beauty_box_jewellery}  //div[@id='hp-parent']//span[text()='เครื่องประดับ']
${EN_search_compare_save_fashion_beauty_box_watches}  //div[@id='hp-parent']//span[text()='Watches']
${VN_search_compare_save_fashion_beauty_box_watches}  //div[@id='hp-parent']//span[text()='Đồng hồ']
${ID_search_compare_save_fashion_beauty_box_watches}  //div[@id='hp-parent']//span[text()='Jam Tangan']
${TH_search_compare_save_fashion_beauty_box_watches}  //div[@id='hp-parent']//span[text()='นาฬิกาข้อมือ']
${EN_search_compare_save_fashion_beauty_box_see_all_categories}  //div[@id='hp-parent']//div[@id='model']//span[text()='See all categories ❯']
${VN_search_compare_save_fashion_beauty_box_see_all_categories}  //div[@id='hp-parent']//div[@id='model']//span[text()='Xem tất cả danh mục ❯']
${ID_search_compare_save_fashion_beauty_box_see_all_categories}  //div[@id='hp-parent']//div[@id='model']//span[text()='Lihat semua kategori ❯']
${TH_search_compare_save_fashion_beauty_box_see_all_categories}  //div[@id='hp-parent']//div[@id='model']//span[text()='เลือกดูหมวดหมู่ทั้งหมด ❯']
${EN_search_compare_save_fashion_beauty_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='model']//span[text()='Shop by brands ❯']
${VN_search_compare_save_fashion_beauty_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='model']//span[text()='Chọn mua theo Thương Hiệu ❯']
${ID_search_compare_save_fashion_beauty_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='model']//span[text()='Belanja berdasarkan Merek ❯']
${TH_search_compare_save_fashion_beauty_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='model']//span[text()='เลือกซื้อจากแบรนด ❯']

${EN_search_compare_save_coupons_offers_box_electronics}  //div[@id='hp-parent']//span[text()='Electronics']
${VN_search_compare_save_coupons_offers_box_electronics}  //div[@id='hp-parent']//span[text()='Điện máy']
${ID_search_compare_save_coupons_offers_box_electronics}  //div[@id='hp-parent']//span[text()='Elektronik']
${TH_search_compare_save_coupons_offers_box_electronics}  //div[@id='hp-parent']//span[text()='อิเล็คทรอนิกส์ & Gadget']
${EN_search_compare_save_coupons_offers_box_fashion}  //div[@id='hp-parent']//span[text()='Fashion']
${VN_search_compare_save_coupons_offers_box_fashion}  //div[@id='hp-parent']//span[text()='Thời trang']
${ID_search_compare_save_coupons_offers_box_fashion}  //div[@id='hp-parent']//span[text()='Fashion & Kecantikan']
${TH_search_compare_save_coupons_offers_box_fashion}  //div[@id='hp-parent']//span[text()='แฟชั่น']
${EN_search_compare_save_coupons_offers_box_beauty_health}  //div[@id='hp-parent']//span[text()='Beauty & Health']
${VN_search_compare_save_coupons_offers_box_beauty_health}  //div[@id='hp-parent']//span[text()='Sức khỏe & Sắc đẹp']
${ID_search_compare_save_coupons_offers_box_beauty_health}  //div[@id='hp-parent']//span[text()='Kesehatan & Kecantikan']
${TH_search_compare_save_coupons_offers_box_beauty_health}  //div[@id='hp-parent']//span[text()='สุขภาพและความงาม']
${EN_search_compare_save_coupons_offers_box_home_living}  //div[@id='hp-parent']//span[text()='Home & Living']
${VN_search_compare_save_coupons_offers_box_home_living}  //div[@id='hp-parent']//span[text()='Nhà cửa & Đời sống']
${ID_search_compare_save_coupons_offers_box_olahraga_outdoor}  //div[@id='hp-parent']//span[text()='Olahraga & Outdoor']
${TH_search_compare_save_coupons_offers_box_home_living}  //div[@id='hp-parent']//span[text()='กีฬา & กิจกรรมกลางแจ้ง']
${EN_search_compare_save_coupons_offers_box_kids_toys}  //div[@id='hp-parent']//span[text()='Kids & Toys']
${VN_search_compare_save_coupons_offers_box_kids_toys}  //div[@id='hp-parent']//span[text()='Trẻ em & Đồ chơi']
${ID_search_compare_save_coupons_offers_box_kids_toys}  //div[@id='hp-parent']//span[text()='Perlengkapan Anak & Mainan']
${TH_search_compare_save_coupons_offers_box_kids_toys}  //div[@id='hp-parent']//span[text()='เด็ก & ของเล่น']
${EN_search_compare_save_coupons_offers_box_travel_hotels}  //div[@id='hp-parent']//span[text()='Travel & Hotels']
${VN_search_compare_save_coupons_offers_box_travel_hotels}  //div[@id='hp-parent']//span[text()='Đồng hồ']
${ID_search_compare_save_coupons_offers_box_travel_hotels}  //div[@id='hp-parent']//span[text()='Wisata & Hotel']
${TH_search_compare_save_coupons_offers_box_travel_hotels}  //div[@id='hp-parent']//span[text()='ท่องเที่ยว & โรงแรม']
${PH_search_compare_save_coupons_offers_box_sports_outdoors}  //div[@id='hp-parent']//span[text()='Sports & Outdoors']
${EN_search_compare_save_coupons_offers_box_see_all_coupons}  //div[@id='hp-parent']//div[@id='offer']//span[text()='See all coupons ❯']
${VN_search_compare_save_coupons_offers_box_see_all_coupons}  //div[@id='hp-parent']//div[@id='offer']//span[text()='Xem tất cả coupon ❯']
${ID_search_compare_save_coupons_offers_box_see_all_coupons}  //div[@id='hp-parent']//div[@id='offer']//span[text()='Lihat semua kupon ❯']
${TH_search_compare_save_coupons_offers_box_see_all_coupons}  //div[@id='hp-parent']//div[@id='offer']//span[text()='เลือกซื้อจากแบรนด ❯']
${EN_search_compare_save_coupons_offers_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='offer']//span[text()='Shop by brands ❯']
${VN_search_compare_save_coupons_offers_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='offer']//span[text()='Chọn mua theo Thương Hiệu ❯']
${ID_search_compare_save_coupons_offers_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='offer']//span[text()='Belanja berdasarkan Merek ❯']
${TH_search_compare_save_coupons_offers_box_shop_by_brands}  //div[@id='hp-parent']//div[@id='offer']//span[text()='เลือกซื้อจากแบรนด ❯']

${modal_signup_close_button}  //div[@id='PopupSignupForm_0']//div[@class='mc-closeModal']

${EN_recommended_products_header}  //div[@id='top-comparable-products']//h2[text()='Recommended Products']
${VN_recommended_products_header}  //div[@id='top-comparable-products']//h2[text()='Sản Phẩm Gợi Ý Cho Bạn']
${ID_recommended_products_header}  //div[@id='top-comparable-products']//h2[text()='Produk yang Direkomendasikan']
${TH_recommended_products_header}  //div[@id='top-comparable-products']//h2[text()='ผลิตภัณฑ์แนะนำ']

${recommended_product_list}  //div[@id='top-comparable-products']//div[@class='product-unit hover-popup offer']

${EN_homepage_footer_international_header}  //section[@id='links']//h3[text()='International']
${VN_homepage_footer_international_header}  //section[@id='links']//h3[text()='Quốc tế']
${ID_homepage_footer_international_header}  //section[@id='links']//h3[text()='Internasional']
${TH_homepage_footer_international_header}  //section[@id='links']//h3[text()='เลือกประเทศ']

${EN_homepage_footer_international_malaysia_link}  //section[@id='links']//a[contains(@href,'https://iprice.my/') and normalize-space(text()='Malaysia')]
${EN_homepage_footer_international_singapore_link}  //section[@id='links']//a[contains(@href,'https://iprice.sg/') and normalize-space(text()='Singapore')]
${EN_homepage_footer_international_indonesia_link}  //section[@id='links']//a[contains(@href,'https://iprice.co.id/') and normalize-space(text()='Indonesia')]
${EN_homepage_footer_international_philippines_link}  //section[@id='links']//a[contains(@href,'https://iprice.ph/') and normalize-space(text()='Philippines')]
${EN_homepage_footer_international_hong_kong_link}  //section[@id='links']//a[contains(@href,'https://iprice.hk/') and normalize-space(text()='Hong Kong')]
${EN_homepage_footer_international_thailand_link}  //section[@id='links']//a[contains(@href,'https://ipricethailand.com/') and normalize-space(text()='Thailand')]
${EN_homepage_footer_international_vietnam_link}  //section[@id='links']//a[contains(@href,'https://iprice.vn/') and normalize-space(text()='Vietnam')]

${VN_homepage_footer_international_malaysia_link}  //section[@id='links']//a[contains(@href,'https://iprice.my/') and normalize-space(text()='Ma-lai-xi-a')]
${VN_homepage_footer_international_singapore_link}  //section[@id='links']//a[contains(@href,'https://iprice.sg/') and normalize-space(text()='Xin-ga-po')]
${VN_homepage_footer_international_indonesia_link}  //section[@id='links']//a[contains(@href,'https://iprice.co.id/') and normalize-space(text()='In-đô-nê-xi-a')]
${VN_homepage_footer_international_philippines_link}  //section[@id='links']//a[contains(@href,'https://iprice.ph/') and normalize-space(text()='Phi-líp-pin')]
${VN_homepage_footer_international_hong_kong_link}  //section[@id='links']//a[contains(@href,'https://iprice.hk/') and normalize-space(text()='Hồng Kông')]
${VN_homepage_footer_international_thailand_link}  //section[@id='links']//a[contains(@href,'https://ipricethailand.com/') and normalize-space(text()='Thái Lan')]

${ID_homepage_footer_international_malaysia_link}  //section[@id='links']//a[contains(@href,'https://iprice.my/') and normalize-space(text()='Malaysia')]
${ID_homepage_footer_international_singapore_link}  //section[@id='links']//a[contains(@href,'https://iprice.sg/') and normalize-space(text()='Singapura')]
${ID_homepage_footer_international_philippines_link}  //section[@id='links']//a[contains(@href,'https://iprice.ph/') and normalize-space(text()='Filipina')]
${ID_homepage_footer_international_hong_kong_link}  //section[@id='links']//a[contains(@href,'https://iprice.hk/') and normalize-space(text()='Hongkong')]
${ID_homepage_footer_international_thailand_link}  //section[@id='links']//a[contains(@href,'https://ipricethailand.com/') and normalize-space(text()='Thailand')]
${ID_homepage_footer_international_vietnam_link}  //section[@id='links']//a[contains(@href,'https://iprice.vn/') and normalize-space(text()='Vietnam')]

${TH_homepage_footer_international_malaysia_link}  //section[@id='links']//a[contains(@href,'https://iprice.my/') and normalize-space(text()='มาเลเซีย')]
${TH_homepage_footer_international_singapore_link}  //section[@id='links']//a[contains(@href,'https://iprice.sg/') and normalize-space(text()='สิงคโปร์')]
${TH_homepage_footer_international_indonesia_link}  //section[@id='links']//a[contains(@href,'https://iprice.co.id/') and normalize-space(text()='อินโดนีเซีย')]
${TH_homepage_footer_international_philippines_link}  //section[@id='links']//a[contains(@href,'https://iprice.ph/') and normalize-space(text()='ฟิลิปปินส์')]
${TH_homepage_footer_international_hong_kong_link}  //section[@id='links']//a[contains(@href,'https://iprice.hk/') and normalize-space(text()='ฮ่องกง')]
${TH_homepage_footer_international_vietnam_link}  //section[@id='links']//a[contains(@href,'https://iprice.vn/') and normalize-space(text()='เวียดนาม')]

${EN_homepage_footer_ipricegroup_header}  //div[@class='ipricegroup']//h3[text()='iPrice group']
${VN_homepage_footer_ipricegroup_header}  //div[@class='ipricegroup']//h3[text()='Tập đoàn iPrice']
${ID_homepage_footer_ipricegroup_header}  //div[@class='ipricegroup']//h3[text()='iPrice group']
${TH_homepage_footer_ipricegroup_header}  //div[@class='ipricegroup']//h3[text()='ทีม iPrice']

${MY_footer_ipricegroup_about_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='About Us')]
${MY_footer_ipricegroup_trends_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.my/trends/') and normalize-space(text()='Trends')]
${MY_footer_ipricegroup_contact_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='Contact Us')]
${MY_footer_ipricegroup_carreers_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='Careers')]
${MY_footer_ipricegroup_partners_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='Partners')]
${MY_footer_ipricegroup_privacy_policy_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.my/privacy-policy/') and normalize-space(text()='Privacy Policy')]
${MY_footer_ipricegroup_terms_of_use_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.my/terms-of-use/') and normalize-space(text()='Terms of Use')]
${MY_footer_ipricegroup_iema_link}    //div[@class='ipricegroup']//a[contains(@href,'https://iprice.my/iema/2016/') and normalize-space(text()='iEMA')]

${VN_footer_ipricegroup_about_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='Giới Thiệu')]
${VN_footer_ipricegroup_trends_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.vn/xu-huong/') and normalize-space(text()='Xu hướng')]
${VN_footer_ipricegroup_contact_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='Liên Hệ')]
${VN_footer_ipricegroup_carreers_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='Tuyển dụng')]
${VN_footer_ipricegroup_partners_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='Đối tác')]
${VN_footer_ipricegroup_privacy_policy_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.vn/privacy-policy/') and normalize-space(text()='Chính sách bảo mật')]
${VN_footer_ipricegroup_terms_of_use_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.vn/terms-of-use/') and normalize-space(text()='Điều khoản & Điều kiện')]
${VN_footer_ipricegroup_iema_link}    //div[@class='ipricegroup']//a[contains(@href,'https://iprice.vn/iema/2016/') and normalize-space(text()='iEMA')]

${ID_footer_ipricegroup_about_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='Tentang Kami')]
${ID_footer_ipricegroup_trends_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.co.id/trend/') and normalize-space(text()='Trend')]
${ID_footer_ipricegroup_contact_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='Hubungi Kami')]
${ID_footer_ipricegroup_carreers_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='Karir')]
${ID_footer_ipricegroup_partners_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='Mitra')]
${ID_footer_ipricegroup_privacy_policy_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.co.id/privacy-policy/') and normalize-space(text()='Kebijakan Privasi')]
${ID_footer_ipricegroup_terms_of_use_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.co.id/terms-of-use/') and normalize-space(text()='Syarat & Ketentuan')]
${ID_footer_ipricegroup_iema_link}    //div[@class='ipricegroup']//a[contains(@href,'https://iprice.co.id/iema/2016/') and normalize-space(text()='iEMA')]

${SG_footer_ipricegroup_about_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='About Us')]
${SG_footer_ipricegroup_trends_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.sg/trends/') and normalize-space(text()='Trends')]
${SG_footer_ipricegroup_contact_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='Contact Us')]
${SG_footer_ipricegroup_carreers_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='Careers')]
${SG_footer_ipricegroup_partners_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='Partners')]
${SG_footer_ipricegroup_privacy_policy_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.sg/privacy-policy/') and normalize-space(text()='Privacy Policy')]
${SG_footer_ipricegroup_terms_of_use_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.sg/terms-of-use/') and normalize-space(text()='Terms of Use')]
${SG_footer_ipricegroup_iema_link}    //div[@class='ipricegroup']//a[contains(@href,'https://iprice.sg/iema/2016/') and normalize-space(text()='iEMA')]

${PH_footer_ipricegroup_about_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='About Us')]
${PH_footer_ipricegroup_trends_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.ph/trends/') and normalize-space(text()='Trends')]
${PH_footer_ipricegroup_contact_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='Contact Us')]
${PH_footer_ipricegroup_carreers_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='Careers')]
${PH_footer_ipricegroup_partners_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='Partners')]
${PH_footer_ipricegroup_privacy_policy_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.ph/privacy-policy/') and normalize-space(text()='Privacy Policy')]
${PH_footer_ipricegroup_terms_of_use_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.ph/terms-of-use/') and normalize-space(text()='Terms of Use')]
${PH_footer_ipricegroup_iema_link}    //div[@class='ipricegroup']//a[contains(@href,'https://iprice.ph/iema/2016/') and normalize-space(text()='iEMA')]

${HK_footer_ipricegroup_about_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='About Us')]
${HK_footer_ipricegroup_trends_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.hk/trends/') and normalize-space(text()='Trends')]
${HK_footer_ipricegroup_contact_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='Contact Us')]
${HK_footer_ipricegroup_carreers_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='Careers')]
${HK_footer_ipricegroup_partners_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='Partners')]
${HK_footer_ipricegroup_privacy_policy_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.hk/privacy-policy/') and normalize-space(text()='Privacy Policy')]
${HK_footer_ipricegroup_terms_of_use_link}  //div[@class='ipricegroup']//a[contains(@href,'https://iprice.hk/terms-of-use/') and normalize-space(text()='Terms of Use')]
${HK_footer_ipricegroup_iema_link}    //div[@class='ipricegroup']//a[contains(@href,'https://iprice.hk/iema/2016/') and normalize-space(text()='iEMA')]

${TH_footer_ipricegroup_about_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='เกี่ยวกับเรา')]
${TH_footer_ipricegroup_trends_link}  //div[@class='ipricegroup']//a[contains(@href,'https://ipricethailand.com/%E0%B9%80%E0%B8%97%E0%B8%A3%E0%B8%99%E0%B8%94/') and normalize-space(text()='เทรนด์')]
${TH_footer_ipricegroup_contact_us_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='ติดต่อเรา')]
${TH_footer_ipricegroup_carreers_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='ร่วมงานกับเรา')]
${TH_footer_ipricegroup_partners_link}  //div[@class='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='พันธมิตร')]
${TH_footer_ipricegroup_privacy_policy_link}  //div[@class='ipricegroup']//a[contains(@href,'https://ipricethailand.com/privacy-policy/') and normalize-space(text()='นโยบายความเป็นส่วนตัว')]
${TH_footer_ipricegroup_terms_of_use_link}  //div[@class='ipricegroup']//a[contains(@href,'https://ipricethailand.com/terms-of-use/') and normalize-space(text()='ข้อตกลงและเงื่อนไข')]
${TH_footer_ipricegroup_iema_link}    //div[@class='ipricegroup']//a[contains(@href,'https://ipricethailand.com/iema/2016/') and normalize-space(text()='iEMA')]

${EN_footer_social_header}  //div[@class='social']//h3[text()='Social']
${VN_footer_social_header}  //div[@class='social']//h3[text()='Mạng xã hội']
${ID_footer_social_header}  //div[@class='social']//h3[text()='Sosial']
${TH_footer_social_header}  //div[@class='social']//h3[text()='ติดตามiPrice']

${MY_footer_social_facebook_link}  //div[@class='social']//a[contains(@href,'https://www.facebook.com/ipriceMalaysia') and normalize-space(text()='Facebook')]
${VN_footer_social_facebook_link}  //div[@class='social']//a[contains(@href,'https://www.facebook.com/vietnamiprice') and normalize-space(text()='Facebook')]
${ID_footer_social_facebook_link}  //div[@class='social']//a[contains(@href,'https://www.facebook.com/ipriceIndonesia') and normalize-space(text()='Facebook')]
${SG_footer_social_facebook_link}  //div[@class='social']//a[contains(@href,'https://www.facebook.com/ipriceSingapore') and normalize-space(text()='Facebook')]
${PH_footer_social_facebook_link}  //div[@class='social']//a[contains(@href,'https://www.facebook.com/ipricePhilippines') and normalize-space(text()='Facebook')]
${HK_footer_social_facebook_link}  //div[@class='social']//a[contains(@href,'https://www.facebook.com/ipriceHongKong') and normalize-space(text()='Facebook')]
${TH_footer_social_facebook_link}  //div[@class='social']//a[contains(@href,'https://www.facebook.com/ipriceThailand') and normalize-space(text()='Facebook')]

${MY_footer_social_pinterest_link}  //div[@class='social']//a[contains(@href,'https://www.pinterest.com/ipricemy') and normalize-space(text()='Pinterest')]
${VN_footer_social_pinterest_link}  //div[@class='social']//a[contains(@href,'https://www.pinterest.com/ipricevn') and normalize-space(text()='Pinterest')]
${ID_footer_social_pinterest_link}  //div[@class='social']//a[contains(@href,'https://www.pinterest.com/ipriceid') and normalize-space(text()='Pinterest')]
${SG_footer_social_pinterest_link}  //div[@class='social']//a[contains(@href,'https://www.pinterest.com/ipricesg') and normalize-space(text()='Pinterest')]
${PH_footer_social_pinterest_link}  //div[@class='social']//a[contains(@href,'https://www.pinterest.com/ipriceph') and normalize-space(text()='Pinterest')]
${HK_footer_social_pinterest_link}  //div[@class='social']//a[contains(@href,'https://www.pinterest.com/ipricehk') and normalize-space(text()='Pinterest')]
${TH_footer_social_pinterest_link}  //div[@class='social']//a[contains(@href,'https://www.pinterest.com/ipriceth') and normalize-space(text()='Pinterest')]

${MY_footer_social_twitter_link}  //div[@class='social']//a[contains(@href,'https://twitter.com/iPriceMY') and normalize-space(text()='Twitter')]
${VN_footer_social_twitter_link}  //div[@class='social']//a[contains(@href,'https://twitter.com/iPriceVN') and normalize-space(text()='Twitter')]
${ID_footer_social_twitter_link}  //div[@class='social']//a[contains(@href,'https://twitter.com/iPriceID') and normalize-space(text()='Twitter')]
${SG_footer_social_twitter_link}  //div[@class='social']//a[contains(@href,'https://twitter.com/iPriceSG') and normalize-space(text()='Twitter')]
${PH_footer_social_twitter_link}  //div[@class='social']//a[contains(@href,'https://twitter.com/iPricePH') and normalize-space(text()='Twitter')]
${HK_footer_social_twitter_link}  //div[@class='social']//a[contains(@href,'https://twitter.com/iPriceHK') and normalize-space(text()='Twitter')]
${TH_footer_social_twitter_link}  //div[@class='social']//a[contains(@href,'https://twitter.com/iPriceTH') and normalize-space(text()='Twitter')]

${all_footer_social_google+_text}  //div[@class='social']//a[contains(@href,'http://plus.google.com/') and normalize-space(text()='Google+')]

${MY_footer_iprice_logo}  //div[@class='flex wrapper en_my']
${VN_footer_iprice_logo}  //div[@class='flex wrapper vi']
${ID_footer_iprice_logo}  //div[@class='flex wrapper id']
${SG_footer_iprice_logo}  //div[@class='flex wrapper en_sg']
${PH_footer_iprice_logo}  //div[@class='flex wrapper en_ph']
${HK_footer_iprice_logo}  //div[@class='flex wrapper en_hk']
${TH_footer_iprice_logo}  //div[@class='flex wrapper th']

${EN_footer_disclaimer_copyright}  //section[@id='disclaimer']//small[text()='© 2017 iPrice Group Sdn Bhd (1113954 - D). All rights reserved.']
${VN_footer_disclaimer_copyright}  //section[@id='disclaimer']//small[text()='©2017 iPrice Group Sdn. Bhd. (1113954 - D). All rights reserved.']
${ID_footer_disclaimer_copyright}  //section[@id='disclaimer']//small[text()='Hak Cipta © 2017 iPrice Group Sdn. Bhd. (1113954 - D).']
${TH_footer_disclaimer_copyright}  //section[@id='disclaimer']//small[text()='© 2017 iPrice Group Sdn. Bhd. (1113954 - D). สงวนลิขสิทธิ์']

${EN_footer_disclaimer_notes}  //section[@id='disclaimer']//p[text()='The prices stated may have increased since the last update. Unfortunately it is not possible for us to update the prices on our website in real-time. Should a shop not offer prices in your local currency, we may calculate the displayed price on daily updated exchange rates.']
${VN_footer_disclaimer_notes}  //section[@id='disclaimer']//p[text()='Giá cả hiển thị có thể cao hơn so với lần cập nhật gần nhất. Chúng tôi rất tiếc vì không thể cập nhật liên tục giá cả niêm yết trên trang web cửa hàng theo từng thời điểm. Trong trường hợp bạn không tìm thấy giá sản phẩm trên website của nhà cung cấp theo VND, chúng tôi sẽ tự động cập nhật dựa trên tỉ giá ngoại tệ hẳng ngày.']
${ID_footer_disclaimer_notes}  //section[@id='disclaimer']//p[text()='Harga yang dinyatakan mungkin telah berubah sejak update terakhir. Namun, tidak memungkinkan bagi kami untuk memperbarui harga di website kami dengan segera. Jika toko tidak menawarkan harga dalam mata uang lokal Anda, kami dapat menghitung harga dan menampilkannya dengan nilai tukar harian yang diperbarui.']
${TH_footer_disclaimer_notes}  //section[@id='disclaimer']//p[text()='ราคาที่แสดงอาจเพิ่มขึ้นหลังจากการอัพเดท ซึ่งทางเราไม่สามารถอัพเดทราคาหน้าเว็บไซต์ได้ตลอดเวลา หากร้านค้าไม่แสดงราคาสินค้าในสกุลเงินของคุณ ทางเราจะแสดงราคาตามอัตราแลกเปลี่ยนประจำวัน']

${COOD_says_url}  http://coupon.says.com/
${COOD_says_title}  Discount Codes, Coupons & Promos | coupon.says.com
${COOD_says_navbar_header_logo}  //div[@class='container']//a[contains(@href,'http://says.com') and text()='SAYS']
${COOD_says_navbar_header_news}  //div[@class='container']//a[contains(@href,'http://says.com/my/news') and text()='NEWS']
${COOD_says_navbar_header_fun}  //div[@class='container']//a[contains(@href,'http://says.com/my/fun') and text()='FUN']
${COOD_says_navbar_header_lifestyle}  //div[@class='container']//a[contains(@href,'http://says.com/my/lifestyle') and text()='LIFESTYLE']
${COOD_says_navbar_header_entertainment}  //div[@class='container']//a[contains(@href,'http://says.com/my/entertainment') and text()='ENTERTAINMENT']
${COOD_says_navbar_header_sport}  //div[@class='container']//a[contains(@href,'http://says.com/my/sports') and text()='SPORTS']
${COOD_says_navbar_header_tech}  //div[@class='container']//a[contains(@href,'http://says.com/my/tech') and text()='TECH']
${COOD_says_navbar_header_imho}  //div[@class='container']//a[contains(@href,'http://says.com/my/imho') and text()='IMHO']
${COOD_says_navbar_header_seismik}  //div[@class='container']//a[contains(@href,'http://says.com/my/seismik') and text()='SEISMIK']
${COOD_says_navbar_header_coupons}  //div[@class='container']//a[contains(@href,'http://coupon.says.com/') and text()='COUPONS']
${COOD_says_banner}  //div[@id='coupon-overview']//div[@class='banner']
${COOD_says_categories_header}  //div[@id='coupon-overview']//span[text()='Categories']
${COOD_says_top_coupons_header}  //div[@id='coupon-overview']//span[text()=' Top Coupons ']
${COOD_says_recent_coupons_header}  //div[@id='coupon-overview']//span[text()=' Recent Coupons ']
${COOD_says_featured_stores_header}  //div[@id='coupon-overview']//span[text()='Featured Stores']
${COOD_says_content_header}  //div[@id='coupon-overview']//strong[text()='Online Shopping – a phenomenal living life style through the decade']
${COOD_says_footer_logo}  //div[@class='container']//div[@class='logo-xs']

${COOD_rappler_en_url}  http://coupons.rappler.com/
${COOD_rappler_en_title}  Promo codes, Coupons & Discount codes | Rappler.com
${COOD_rappler_en_navbar_header_logo}  //div[@class='menu-trigger nav-full']//img[@class='thinglinkFiltered']
${COOD_rappler_en_navbar_header_ph}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/') and text()='Philippines']
${COOD_rappler_en_navbar_header_id}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/indonesia/') and text()='Indonesia']
${COOD_rappler_en_header}  //div[@id='coupon-overview']//h1[text()=' Coupons on Rappler.com ']
${COOD_rappler_en_featured_coupons_header}  //div[@id='coupon-overview']//h2[text()='Featured Coupons']
${COOD_rappler_en_categories_header}  //div[@id='coupon-overview']//h1[text()='Categories']
${COOD_rappler_en_popular_coupons_header}  //div[@id='coupon-overview']//h1[text()='Popular Coupons']
${COOD_rappler_en_latest_coupons_header}  //div[@id='coupon-overview']//h1[text()='Latest Coupons']
${COOD_rappler_en_content_area}  //div[@id='coupon-overview']//div[@class='content-text']
${COOD_rappler_en_footer_area}  //div[@id='footer-wrapper']

${COOD_rappler_id_url}  http://kupon.rappler.com/
${COOD_rappler_id_title}  Promo Kode, Kupon, Diskon Kode, Sale & Voucher di Agustus 2017 | Rappler Indonesia
${COOD_rappler_id_navbar_header_logo}  //div[@class='menu-trigger nav-full']//img[@class='thinglinkFiltered']
${COOD_rappler_id_navbar_header_ph}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/') and text()='Philippines']
${COOD_rappler_id_navbar_header_id}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/indonesia/') and text()='Indonesia']
${COOD_rappler_id_header}  //div[@id='coupon-overview']//h1[text()=' Beragam Kupon Pilihan di Rappler.com ']
${COOD_rappler_id_featured_coupons_header}  //div[@id='coupon-overview']//h2[text()='Beragam Kupon Pilihan']
${COOD_rappler_id_categories_header}  //div[@id='coupon-overview']//h1[text()='Kategori']
${COOD_rappler_id_popular_coupons_header}  //div[@id='coupon-overview']//h1[text()='Kupon Terpopuler']
${COOD_rappler_id_latest_coupons_header}  //div[@id='coupon-overview']//h1[text()='Kupon Terbaru']
${COOD_rappler_id_content_area}  //div[@id='coupon-overview']//div[@class='content-text']
${COOD_rappler_id_footer_area}  //div[@id='footer-wrapper']
