*** Settings ***
Documentation  This file will only store variables for MY.
*** Variables ***

${MY_homeURL}  https://iprice.my/?nocache=1
${MY_homeTitle}  Online Shopping, Coupons & Discount Codes at iprice Malaysia

${MY_header_H1_text}  //h1[text()='Search, Compare & Save']
${MY_header_logo}  //div[@id='logo']
${MY_header_logo_link}  //div[@id='logo']//a[@href='https://iprice.my/']
${MY_header_search_input}  //div[@id='search']//input[@placeholder='Search for products, coupons or brands...']
${MY_header_search_icon}  //div[@id='search']//i[@class='icon icon-search-blue']
${MY_header_popular_searches_text}  //div[@id='popular-searches']//li[normalize-space(text())='Popular Searches:']
${MY_header_coupon_logo_link}  //div[@id='news-button']//a[@href='https://iprice.my/coupons/']
${MY_header_coupon_text}  //div[@id='news-button']//button[normalize-space(text())='Coupons & Offers']
${MY_header_categories_clothing_link}  //div[@id='menu']//a[@href='https://iprice.my/clothing/']//span[text()='Clothing']
${MY_header_categories_clothing_men}  //div[@id='menu']//a[contains(@href,'https://iprice.my/clothing/men/') and text()='Men']
${MY_header_categories_clothing_men_belts}  //div[@id='menu']//a[contains(@href,'https://iprice.my/clothing/men/belts/') and text()='Belts']
${MY_header_categories_clothing_women}  //div[@id='menu']//a[contains(@href,'https://iprice.my/clothing/women/') and text()='Women']
${MY_header_categories_clothing_women_beanies}  //div[@id='menu']//a[contains(@href,'https://iprice.my/clothing/women/beanies/') and text()='Beanies']
${MY_header_categories_shoes_link}  //div[@id='menu']//a[@href='https://iprice.my/shoes/']//span[text()='Shoes']
${MY_header_categories_shoes_men}  //div[@id='menu']//a[contains(@href,'https://iprice.my/shoes/men/') and text()='Men']
${MY_header_categories_shoes_men_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/shoes/men/accessories/') and text()='Accessories']
${MY_header_categories_shoes_women}  //div[@id='menu']//a[contains(@href,'https://iprice.my/shoes/women/') and text()='Women']
${MY_header_categories_shoes_women_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/shoes/women/accessories/') and text()='Accessories']
${MY_header_categories_bags_link}  //div[@id='menu']//a[@href='https://iprice.my/bags/']//span[text()='Bags']
${MY_header_categories_bags_bag_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/bags/accessories/') and text()='Bag Accessories']
${MY_header_categories_bags_backpacks}  //div[@id='menu']//a[contains(@href,'https://iprice.my/bags/backpacks/') and text()='Backpacks']
${MY_header_categories_bags_briefcases}  //div[@id='menu']//a[contains(@href,'https://iprice.my/bags/briefcases/') and text()='Briefcases']
${MY_header_categories_bags_cooler_bags}  //div[@id='menu']//a[contains(@href,'https://iprice.my/bags/cooler/') and text()='Cooler Bags']
${MY_header_categories_watches_link}  //div[@id='menu']//a[@href='https://iprice.my/watches/']//span[text()='Watches']
${MY_header_categories_watches_analogue_watches}  //div[@id='menu']//a[contains(@href,'https://iprice.my/watches/analogue/') and text()='Analogue Watches']
${MY_header_categories_watches_chronograph_watches}  //div[@id='menu']//a[contains(@href,'https://iprice.my/watches/chronograph/') and text()='Chronograph Watches']
${MY_header_categories_watches_couple_watches}  //div[@id='menu']//a[contains(@href,'https://iprice.my/watches/couple/') and text()='Couple Watches']
${MY_header_categories_watches_digital_watches}  //div[@id='menu']//a[contains(@href,'https://iprice.my/watches/digital/') and text()='Digital Watches']
${MY_header_categories_jewellery_link}  //div[@id='menu']//a[@href='https://iprice.my/jewellery/']//span[text()='Jewellery']
${MY_header_categories_jewellery_jewellery_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/jewellery/accessories/') and text()='Jewellery Accessories']
${MY_header_categories_jewellery_anklet}  //div[@id='menu']//a[contains(@href,'https://iprice.my/jewellery/anklet/') and text()='Anklet']
${MY_header_categories_jewellery_beads}  //div[@id='menu']//a[contains(@href,'https://iprice.my/jewellery/beads/') and text()='Beads']
${MY_header_categories_jewellery_bracelets}  //div[@id='menu']//a[contains(@href,'https://iprice.my/jewellery/bracelets/') and text()='Bracelets']
${MY_header_categories_computing_link}  //div[@id='menu']//a[@href='https://iprice.my/computing/']//span[text()='Computing']
${MY_header_categories_computing_computing_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/computing/accessories/') and text()='Computing Accessories']
${MY_header_categories_computing_desktop_pcs}  //div[@id='menu']//a[contains(@href,'https://iprice.my/computing/desktop-pcs/') and text()='Desktop PCs']
${MY_header_categories_computing_external_storage}  //div[@id='menu']//a[contains(@href,'https://iprice.my/computing/external-storage/') and text()='External Storage']
${MY_header_categories_computing_hardware}  //div[@id='menu']//a[contains(@href,'https://iprice.my/computing/hardware/') and text()='Hardware']
${MY_header_categories_phones_tablets_link}  //div[@id='menu']//a[@href='https://iprice.my/phones-tablets/']//span[text()='Phones & Tablets']
${MY_header_categories_phones_tablets_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/phones-tablets/accessories/') and text()='Phones & Tablets Accessories']
${MY_header_categories_phones_tablets_basic_phones}  //div[@id='menu']//a[contains(@href,'https://iprice.my/phones-tablets/basic-phones/') and text()='Basic Phones']
${MY_header_categories_phones_tablets_bluetooth_headsets}  //div[@id='menu']//a[contains(@href,'https://iprice.my/phones-tablets/bluetooth-headsets/') and text()='Bluetooth Headsets']
${MY_header_categories_phones_tablets_landline_phones}  //div[@id='menu']//a[contains(@href,'https://iprice.my/phones-tablets/landline/') and text()='Landline Phones']
${MY_header_categories_gaming_link}  //div[@id='menu']//a[@href='https://iprice.my/gaming/']//span[text()='Gaming']
${MY_header_categories_gaming_gaming_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/gaming/accessories/') and text()='Gaming Accessories']
${MY_header_categories_gaming_gaming_controllers}  //div[@id='menu']//a[contains(@href,'https://iprice.my/gaming/controllers/') and text()='Gaming Controllers']
${MY_header_categories_gaming_games}  //div[@id='menu']//a[contains(@href,'https://iprice.my/gaming/games/') and text()='Games']
${MY_header_categories_gaming_mobile}  //div[@id='menu']//a[contains(@href,'https://iprice.my/gaming/mobile/') and text()='Mobile']
${MY_header_categories_camera_photo_link}  //div[@id='menu']//a[@href='https://iprice.my/camera-photo/']//span[text()='Camera & Photo']
${MY_header_categories_camera_photo_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/camera-photo/accessories/') and text()='Camera Accessories']
${MY_header_categories_camera_photo_action_cameras}  //div[@id='menu']//a[contains(@href,'https://iprice.my/camera-photo/action/') and text()='Action Cameras']
${MY_header_categories_camera_photo_CCTV_cameras}  //div[@id='menu']//a[contains(@href,'https://iprice.my/camera-photo/cctv/') and text()='CCTV Cameras']
${MY_header_categories_camera_photo_camcorders}  //div[@id='menu']//a[contains(@href,'https://iprice.my/camera-photo/camcorders/') and text()='Camcorders']
${MY_header_categories_tv_video_dvd_link}  //div[@id='menu']//a[@href='https://iprice.my/tv-video-dvd/']//span[text()='TV, Video & DVD']
${MY_header_categories_tv_video_dvd_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/tv-video-dvd/accessories/') and text()='TV, Video & DVD Accessories']
${MY_header_categories_tv_video_dvd_Blu-Ray}  //div[@id='menu']//a[contains(@href,'https://iprice.my/tv-video-dvd/blu-ray/') and text()='Blu-Ray']
${MY_header_categories_tv_video_dvd_DVD_Players}  //div[@id='menu']//a[contains(@href,'https://iprice.my/tv-video-dvd/dvd-players/') and text()='DVD Players']
${MY_header_categories_tv_video_dvd_HDMI_media_players}  //div[@id='menu']//a[contains(@href,'https://iprice.my/tv-video-dvd/hdmi-media-players/') and text()='HDMI Media Players']
${MY_header_categories_appliances_link}  //div[@id='menu']//a[@href='https://iprice.my/appliances/']//span[text()='Appliances']
${MY_header_categories_appliances_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/appliances/accessories/') and text()='Accessories']
${MY_header_categories_appliances_air_conditioners}  //div[@id='menu']//a[contains(@href,'https://iprice.my/appliances/air-conditioners/') and text()='Air Conditioners']
${MY_header_categories_appliances_air_purifiers}  //div[@id='menu']//a[contains(@href,'https://iprice.my/appliances/air-purifiers/') and text()='Air Purifiers']
${MY_header_categories_appliances_blenders}  //div[@id='menu']//a[contains(@href,'https://iprice.my/appliances/blenders/') and text()='Blenders']
${MY_header_categories_cars_link}  //div[@id='menu']//a[@href='https://iprice.my/cars/']//span[text()='Cars']
${MY_header_categories_cars_classic}  //div[@id='menu']//a[contains(@href,'https://iprice.my/cars/classic/') and text()='Classic Cars']
${MY_header_categories_cars_commercials}  //div[@id='menu']//a[contains(@href,'https://iprice.my/cars/commercials/') and text()='Commercial Cars']
${MY_header_categories_cars_general}  //div[@id='menu']//a[contains(@href,'https://iprice.my/cars/general/') and text()='General Cars']
${MY_header_categories_cars_MPVs}  //div[@id='menu']//a[contains(@href,'https://iprice.my/cars/mpvs/') and text()='MPV Cars']
${MY_header_categories_automotive_link}  //div[@id='menu']//a[@href='https://iprice.my/automotive/']//span[text()='Automotive']
${MY_header_categories_automotive_car_accessories}  //div[@id='menu']//a[contains(@href,'https://iprice.my/automotive/car-accessories/') and text()='Car Accessories']
${MY_header_categories_automotive_car_care}  //div[@id='menu']//a[contains(@href,'https://iprice.my/automotive/car-care/') and text()='Car Care']
${MY_header_categories_automotive_cars}  //div[@id='menu']//a[contains(@href,'https://iprice.my/automotive/cars/') and text()='Cars']
${MY_header_categories_automotive_cars_GPS}  //div[@id='menu']//a[contains(@href,'https://iprice.my/automotive/car-gps/') and text()='Car GPS']
${MY_header_categories_+_categories_link}  //div[@id='menu']//a[contains(@href,'https://iprice.my/categories/') and text()='+ Categories']
${MY_header_categories_hobbies_link}  //div[@id='menu']//a[@href='https://iprice.my/hobbies/']//span[text()='Hobbies']
${MY_header_categories_audio_hifi_link}  //div[@id='menu']//a[@href='https://iprice.my/audio-hi-fi/']//span[text()='Audio & Hi Fi']
${MY_header_categories_action_sport_link}  //div[@id='menu']//a[@href='https://iprice.my/action-sports/']//span[text()='Action Sports']
${MY_header_categories_adventure_link}  //div[@id='menu']//a[@href='https://iprice.my/adventure/']//span[text()='Adventure']
${MY_header_categories_baby_clothing_link}  //div[@id='menu']//a[@href='https://iprice.my/baby-clothing/']//span[text()='Baby Clothing']
${MY_header_categories_baby_gear_link}  //div[@id='menu']//a[@href='https://iprice.my/baby-gear/']//span[text()='Baby Gear']
${MY_header_categories_bath_body_link}  //div[@id='menu']//a[@href='https://iprice.my/bath-body/']//span[text()='Bath & Body']
${MY_header_categories_dental_care_link}  //div[@id='menu']//a[@href='https://iprice.my/dental-care/']//span[text()='Dental Care']
${MY_header_categories_diapering_link}  //div[@id='menu']//a[@href='https://iprice.my/diapering/']//span[text()='Diapering']
${MY_header_categories_eyecare_link}  //div[@id='menu']//a[@href='https://iprice.my/eyecare/']//span[text()='Eyecare']
${MY_header_categories_feeding_link}  //div[@id='menu']//a[@href='https://iprice.my/feeding/']//span[text()='Feeding']
${MY_header_categories_food_supplements_link}  //div[@id='menu']//a[@href='https://iprice.my/food-supplements/']//span[text()='Food Supplements']
${MY_header_categories_gifts_link}  //div[@id='menu']//a[@href='https://iprice.my/gifts/']//span[text()='Gifts']
${MY_header_categories_gym_link}  //div[@id='menu']//a[@href='https://iprice.my/gym/']//span[text()='Gym']
${MY_header_categories_hair_care_link}  //div[@id='menu']//a[@href='https://iprice.my/hair-care/']//span[text()='Hair Care']
${MY_header_categories_health_link}  //div[@id='menu']//a[@href='https://iprice.my/health/']//span[text()='Health']
${MY_header_categories_kids_clothing_link}  //div[@id='menu']//a[@href='https://iprice.my/kids-clothing/']//span[text()='Kids Clothing']
${MY_header_categories_makeup_link}  //div[@id='menu']//a[@href='https://iprice.my/makeup/']//span[text()='Makeup']
${MY_header_categories_maternity_care_link}  //div[@id='menu']//a[@href='https://iprice.my/maternity-care/']//span[text()='Maternity Care']
${MY_header_categories_medical_supplies_link}  //div[@id='menu']//a[@href='https://iprice.my/medical-supplies/']//span[text()='Medical Supplies']
${MY_header_categories_nursery_link}  //div[@id='menu']//a[@href='https://iprice.my/nursery/']//span[text()='Nursery']
${MY_header_categories_perfeum_link}  //div[@id='menu']//a[@href='https://iprice.my/perfume/']//span[text()='Perfume']
${MY_header_categories_racquet_sports_link}  //div[@id='menu']//a[@href='https://iprice.my/racquet-sports/']//span[text()='Racquet Sports']
${MY_header_categories_shaving_supplies_link}  //div[@id='menu']//a[@href='https://iprice.my/shaving-supplies/']//span[text()='Shaving Supplies']
${MY_header_categories_skin_care_link}  //div[@id='menu']//a[@href='https://iprice.my/skin-care/']//span[text()='Skin Care']
${MY_header_categories_supplements_link}  //div[@id='menu']//a[@href='https://iprice.my/supplements/']//span[text()='Supplements']
${MY_header_categories_team_sports_link}  //div[@id='menu']//a[@href='https://iprice.my/team-sports/']//span[text()='Team Sports']
${MY_header_categories_toys_link}  //div[@id='menu']//a[@href='https://iprice.my/toys/']//span[text()='Toys']
${MY_header_categories_water_sports_link}  //div[@id='menu']//a[@href='https://iprice.my/water-sports/']//span[text()='Water Sports']
${MY_header_categories_groceries_link}  //div[@id='menu']//a[@href='https://iprice.my/groceries/']//span[text()='Groceries']
${MY_header_categories_ear_care_link}  //div[@id='menu']//a[@href='https://iprice.my/ear-care/']//span[text()='Ear Care']
${MY_header_categories_bathroom_link}  //div[@id='menu']//a[@href='https://iprice.my/bathroom/']//span[text()='Bathroom']
${MY_header_categories_bedroom_link}  //div[@id='menu']//a[@href='https://iprice.my/bedroom/']//span[text()='Bedroom']
${MY_header_categories_hallway_entry_link}  //div[@id='menu']//a[@href='https://iprice.my/hallway-entry/']//span[text()='Hallway & Entry']
${MY_header_categories_home_decor_link}  //div[@id='menu']//a[@href='https://iprice.my/home-decor/']//span[text()='Home Decor']
${MY_header_categories_home_improvement_link}  //div[@id='menu']//a[@href='https://iprice.my/home-improvement/']//span[text()='Home Improvement']
${MY_header_categories_home_office_link}  //div[@id='menu']//a[@href='https://iprice.my/home-office/']//span[text()='Home Office']
${MY_header_categories_housekeepng_link}  //div[@id='menu']//a[@href='https://iprice.my/housekeeping/']//span[text()='Housekeeping']
${MY_header_categories_kitchen_dining_link}  //div[@id='menu']//a[@href='https://iprice.my/kitchen-dining/']//span[text()='Kitchen & Dining']
${MY_header_categories_lighting_link}  //div[@id='menu']//a[@href='https://iprice.my/lighting/']//span[text()='Lighting']
${MY_header_categories_living_room_link}  //div[@id='menu']//a[@href='https://iprice.my/living-room/']//span[text()='Living Room']
${MY_header_categories_outdoor_garden_link}  //div[@id='menu']//a[@href='https://iprice.my/outdoor-garden/']//span[text()='Outdoor & Garden']
${MY_header_categories_pets_suplies_link}  //div[@id='menu']//a[@href='https://iprice.my/pets-supplies/']//span[text()='Pets Supplies']
${MY_header_categories_security_link}  //div[@id='menu']//a[@href='https://iprice.my/security/']//span[text()='Security']
${MY_header_categories_stationery_link}  //div[@id='menu']//a[@href='https://iprice.my/stationery/']//span[text()='Stationery']
${MY_header_categories_gadgets_link}  //div[@id='menu']//a[@href='https://iprice.my/gadgets/']//span[text()='Gadgets']
# ${MY_header_categories_other_sports_link}  //div[@id='menu']//a[@href='https://iprice.my/other-sports/']//span[text()='Other Sports']
${MY_header_categories_upcoming_products_link}  //div[@id='menu']//a[@href='https://iprice.my/upcoming-products/']//span[text()='Upcoming Products']

${MY_category_clothing_title}  Clothing | The best prices online in Malaysia | iPrice
${MY_category_clothing_header}  //div[@id='products-header']//h1[text()='Clothing']
${MY_category_clothing_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_clothing_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_clothing_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_shoes_link}  https://iprice.my/shoes/
${MY_category_shoes_title}  Shoes | The best prices online in Malaysia | iPrice
${MY_category_shoes_breadcrumb}  //div[@class='crumb-wrapper']//span[text()='Shoes']
${MY_category_shoes_header}  //div[@id='products-header']//h1[text()='Shoes']
${MY_category_shoes_sub_sandal_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/sandals/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_sandal_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/sandals/']//figcaption[@title='Sandals']
${MY_category_shoes_sub_sneakers_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/sneakers/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_sneakers_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/sneakers/']//figcaption[@title='Sneakers']
${MY_category_shoes_sub_sport_shoes_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/sports/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_sport_shoes_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/sports/']//figcaption[@title='Sport Shoes']
${MY_category_shoes_sub_loafers_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/loafers/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_loafers_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/loafers/']//figcaption[@title='Loafers']
${MY_category_shoes_sub_boat_shoes_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/boat/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_boat_shoes_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/boat/']//figcaption[@title='Boat Shoes']
${MY_category_shoes_sub_boots_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/boots/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_boots_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/boots/']//figcaption[@title='Boots']
${MY_category_shoes_sub_flip_flops_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/flip-flops/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_flip_flops_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/flip-flops/']//figcaption[@title='Flip Flops']
${MY_category_shoes_sub_flats_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/flats/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_flats_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/flats/']//figcaption[@title='Flats']
${MY_category_shoes_sub_high_heels_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/high-heels/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_high_heels_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/high-heels/']//figcaption[@title='High Heels']
${MY_category_shoes_sub_kids_baby_shoes_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/kids-and-baby/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_kids_baby_shoes_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/kids-and-baby/']//figcaption[@title='Kids and Baby Shoes']
${MY_category_shoes_sub_pumps_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/pumps/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_pumps_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/pumps/']//figcaption[@title='Pumps']
${MY_category_shoes_sub_wedges_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/wedges/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_wedges_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/wedges/']//figcaption[@title='Wedges']
${MY_category_shoes_sub_platform_shoes_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/platforms/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_platform_shoes_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/platforms/']//figcaption[@title='Platform Shoes']
${MY_category_shoes_sub_brogue_shoes_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/brogues/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_brogue_shoes_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/brogues/']//figcaption[@title='Brogue Shoes']
${MY_category_shoes_sub_safety_shoes_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/safety/']//img[@class='lazy initial loaded']
${MY_category_shoes_sub_safety_shoes_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/safety/']//figcaption[@title='Safety Shoes']
${MY_category_shoes_sub_accessories_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/accessories/']//img[contains(@class,'lazy') and contains(@class,'loaded')]
${MY_category_shoes_sub_accessories_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/accessories/']//figcaption[@title='Shoe Accessories']
${MY_category_shoes_sub_led_shoes_top_filter_image}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/led/']//img[@class='lazy loaded']
${MY_category_shoes_sub_led_shoes_top_filter_text}  //div[@id='related-categories']//a[@href='https://iprice.my/shoes/led/']//figcaption[@title='LED Shoes']
${MY_category_shoes_left_filter_categories_header}  //div[@class='list-item category']//h2[text()='Categories']
${MY_category_shoes_sub_sandal_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/sandals/']//span[text()='Sandals']
${MY_category_shoes_sub_sneakers_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/sneakers/']//span[text()='Sneakers']
${MY_category_shoes_sub_sport_shoes_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/sports/']//span[text()='Sport Shoes']
${MY_category_shoes_sub_loafers_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/loafers/']//span[text()='Loafers']
${MY_category_shoes_sub_boat_shoes_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/boat/']//span[text()='Boat Shoes']
${MY_category_shoes_sub_boots_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/boots/']//span[text()='Boots']
${MY_category_shoes_sub_flip_flops_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/flip-flops/']//span[text()='Flip Flops']
${MY_category_shoes_sub_flats_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/flats/']//span[text()='Flats']
${MY_category_shoes_sub_high_heels_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/high-heels/']//span[text()='High Heels']
${MY_category_shoes_sub_kids_baby_shoes_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/kids-and-baby/']//span[text()='Kids and Baby Shoes']
${MY_category_shoes_sub_pumps_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/pumps/']//span[text()='Pumps']
${MY_category_shoes_sub_wedges_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/wedges/']//span[text()='Wedges']
${MY_category_shoes_sub_platform_shoes_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/platforms/']//span[text()='Platform Shoes']
${MY_category_shoes_sub_brogue_shoes_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/brogues/']//span[text()='Brogue Shoes']
${MY_category_shoes_sub_safety_shoes_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/safety/']//span[text()='Safety Shoes']
${MY_category_shoes_sub_accessories_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/accessories/']//span[text()='Shoe Accessories']
${MY_category_shoes_sub_led_shoes_left_filter_text}  //div[@class='list-item category']//a[@href='https://iprice.my/shoes/led/']//span[text()='LED Shoes']
${MY_category_shoes_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_shoes_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_shoes_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_bags_title}  Bags | The best prices online in Malaysia | iPrice
${MY_category_bags_header}  //div[@id='products-header']//h1[text()='Bags']
${MY_category_bags_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_bags_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_bags_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_watches_title}  Watches | The best prices online in Malaysia | iPrice
${MY_category_watches_header}  //div[@id='products-header']//h1[text()='Watches']
${MY_category_watches_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_watches_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_watches_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_jewellery_title}  Jewellery | The best prices online in Malaysia | iPrice
${MY_category_jewellery_header}  //div[@id='products-header']//h1[text()='Jewellery']
${MY_category_jewellery_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_jewellery_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_jewellery_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_computing_title}  Computing | The best prices online in Malaysia | iPrice
${MY_category_computing_header}  //div[@id='products-header']//h1[text()='Computing']
${MY_category_computing_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_computing_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_computing_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_phones_tablets_title}  Phones & Tablets | The best prices online in Malaysia | iPrice
${MY_category_phones_tablets_header}  //div[@id='products-header']//h1[text()='Phones & Tablets']
${MY_category_phones_tablets_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_phones_tablets_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_phones_tablets_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_gaming_title}  Gaming | The best prices online in Malaysia | iPrice
${MY_category_gaming_header}  //div[@id='products-header']//h1[text()='Gaming']
${MY_category_gaming_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_gaming_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_gaming_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_camera_photo_title}  Camera & Photo | The best prices online in Malaysia | iPrice
${MY_category_camera_photo_header}  //div[@id='products-header']//h1[text()='Camera & Photo']
${MY_category_camera_photo_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_camera_photo_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_camera_photo_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_tv_video_dvd_title}  TV, Video & DVD | The best prices online in Malaysia | iPrice
${MY_category_tv_video_dvd_header}  //div[@id='products-header']//h1[text()='TV, Video & DVD']
${MY_category_tv_video_dvd_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_tv_video_dvd_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_tv_video_dvd_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_appliances_title}  Appliances | The best prices online in Malaysia | iPrice
${MY_category_appliances_header}  //div[@id='products-header']//h1[text()='Appliances']
${MY_category_appliances_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_appliances_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_appliances_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_category_cars_title}  Cars | The best prices online in Malaysia | iPrice
${MY_category_cars_header}  //div[@id='products-header']//h1[text()='Cars']

${MY_category_automotive_title}  Automotive | The best prices online in Malaysia | iPrice
${MY_category_automotive_header}  //div[@id='products-header']//h1[text()='Automotive']
${MY_category_automotive_filter_gender_header}  //div[@id='filters']//h2[text()='Gender']
${MY_category_automotive_filter_gender_men}  //div[@id='filters']//span[text()='Men']
${MY_category_automotive_filter_gender_women}  //div[@id='filters']//span[text()='Women']

${MY_+categories_title}  Categories | iprice Malaysia
${MY_+categories_header}  //div[@id='categories']//h2[text()='Categories']
${MY_+categories_clothing_main}  //div[@id='categories']//a[@href='https://iprice.my/clothing/']//span[text()='Clothing']
${MY_+categories_shoes_main}  //div[@id='categories']//a[@href='https://iprice.my/shoes/']//span[text()='Shoes']
${MY_+categories_bags_main}  //div[@id='categories']//a[@href='https://iprice.my/bags/']//span[text()='Bags']
${MY_+categories_watches_main}  //div[@id='categories']//a[@href='https://iprice.my/watches/']//span[text()='Watches']
${MY_+categories_jewellery_main}  //div[@id='categories']//a[@href='https://iprice.my/jewellery/']//span[text()='Jewellery']
${MY_+categories_computing_main}  //div[@id='categories']//a[@href='https://iprice.my/computing/']//span[text()='Computing']
${MY_+categories_phones_tablets_main}  //div[@id='categories']//a[@href='https://iprice.my/phones-tablets/']//span[text()='Phones & Tablets']
${MY_+categories_gaming_main}  //div[@id='categories']//a[@href='https://iprice.my/gaming/']//span[text()='Gaming']
${MY_+categories_camera_photo_main}  //div[@id='categories']//a[@href='https://iprice.my/camera-photo/']//span[text()='Camera & Photo']
${MY_+categories_tv_video_dvd_main}  //div[@id='categories']//a[@href='https://iprice.my/tv-video-dvd/']//span[text()='TV, Video & DVD']
${MY_+categories_appliances_main}  //div[@id='categories']//a[@href='https://iprice.my/appliances/']//span[text()='Appliances']
${MY_+categories_cars_main}  //div[@id='categories']//a[@href='https://iprice.my/cars/']//span[text()='Cars']
${MY_+categories_automotive_main}  //div[@id='categories']//a[@href='https://iprice.my/automotive/']//span[text()='Automotive']
${MY_+categories_hobbies_main}  //div[@id='categories']//a[@href='https://iprice.my/hobbies/']//span[text()='Hobbies']
${MY_+categories_audio_hifi_main}  //div[@id='categories']//a[@href='https://iprice.my/audio-hi-fi/']//span[text()='Audio & Hi Fi']
${MY_+categories_action_sports_main}  //div[@id='categories']//a[@href='https://iprice.my/action-sports/']//span[text()='Action Sports']
${MY_+categories_adventure_main}  //div[@id='categories']//a[@href='https://iprice.my/adventure/']//span[text()='Adventure']
${MY_+categories_baby_clothing_main}  //div[@id='categories']//a[@href='https://iprice.my/baby-clothing/']//span[text()='Baby Clothing']
${MY_+categories_baby_gear_main}  //div[@id='categories']//a[@href='https://iprice.my/baby-gear/']//span[text()='Baby Gear']
${MY_+categories_bath_body_main}  //div[@id='categories']//a[@href='https://iprice.my/bath-body/']//span[text()='Bath & Body']
${MY_+categories_dental_care_main}  //div[@id='categories']//a[@href='https://iprice.my/dental-care/']//span[text()='Dental Care']
${MY_+categories_diapering_main}  //div[@id='categories']//a[@href='https://iprice.my/diapering/']//span[text()='Diapering']
${MY_+categories_eyecare_main}  //div[@id='categories']//a[@href='https://iprice.my/eyecare/']//span[text()='Eyecare']
${MY_+categories_feeding_main}  //div[@id='categories']//a[@href='https://iprice.my/feeding/']//span[text()='Feeding']
${MY_+categories_food_supplements_main}  //div[@id='categories']//a[@href='https://iprice.my/food-supplements/']//span[text()='Food Supplements']
${MY_+categories_gifts_main}  //div[@id='categories']//a[@href='https://iprice.my/gifts/']//span[text()='Gifts']
${MY_+categories_gym_main}  //div[@id='categories']//a[@href='https://iprice.my/gym/']//span[text()='Gym']
${MY_+categories_hair_care_main}  //div[@id='categories']//a[@href='https://iprice.my/hair-care/']//span[text()='Hair Care']
${MY_+categories_health_main}  //div[@id='categories']//a[@href='https://iprice.my/health/']//span[text()='Health']
${MY_+categories_kids_clothing_main}  //div[@id='categories']//a[@href='https://iprice.my/kids-clothing/']//span[text()='Kids Clothing']
${MY_+categories_makeup_main}  //div[@id='categories']//a[@href='https://iprice.my/makeup/']//span[text()='Makeup']
${MY_+categories_maternity_care_main}  //div[@id='categories']//a[@href='https://iprice.my/maternity-care/']//span[text()='Maternity Care']
${MY_+categories_medical_supplies_main}  //div[@id='categories']//a[@href='https://iprice.my/medical-supplies/']//span[text()='Medical Supplies']
${MY_+categories_nursery_link}  //div[@id='categories']//a[@href='https://iprice.my/nursery/']//span[text()='Nursery']
${MY_+categories_perfeum_link}  //div[@id='categories']//a[@href='https://iprice.my/perfume/']//span[text()='Perfume']
${MY_+categories_racquet_sports_link}  //div[@id='categories']//a[@href='https://iprice.my/racquet-sports/']//span[text()='Racquet Sports']
${MY_+categories_shaving_supplies_link}  //div[@id='categories']//a[@href='https://iprice.my/shaving-supplies/']//span[text()='Shaving Supplies']
${MY_+categories_skin_care_link}  //div[@id='categories']//a[@href='https://iprice.my/skin-care/']//span[text()='Skin Care']
${MY_+categories_supplements_link}  //div[@id='categories']//a[@href='https://iprice.my/supplements/']//span[text()='Supplements']
${MY_+categories_team_sports_link}  //div[@id='categories']//a[@href='https://iprice.my/team-sports/']//span[text()='Team Sports']
${MY_+categories_toys_link}  //div[@id='categories']//a[@href='https://iprice.my/toys/']//span[text()='Toys']
${MY_+categories_water_sports_link}  //div[@id='categories']//a[@href='https://iprice.my/water-sports/']//span[text()='Water Sports']
${MY_+categories_groceries_link}  //div[@id='categories']//a[@href='https://iprice.my/groceries/']//span[text()='Groceries']
${MY_+categories_ear_care_link}  //div[@id='categories']//a[@href='https://iprice.my/ear-care/']//span[text()='Ear Care']
${MY_+categories_bathroom_link}  //div[@id='categories']//a[@href='https://iprice.my/bathroom/']//span[text()='Bathroom']
${MY_+categories_bedroom_link}  //div[@id='categories']//a[@href='https://iprice.my/bedroom/']//span[text()='Bedroom']
${MY_+categories_hallway_entry_link}  //div[@id='categories']//a[@href='https://iprice.my/hallway-entry/']//span[text()='Hallway & Entry']
${MY_+categories_home_decor_link}  //div[@id='categories']//a[@href='https://iprice.my/home-decor/']//span[text()='Home Decor']
${MY_+categories_home_improvement_link}  //div[@id='categories']//a[@href='https://iprice.my/home-improvement/']//span[text()='Home Improvement']
${MY_+categories_home_office_link}  //div[@id='categories']//a[@href='https://iprice.my/home-office/']//span[text()='Home Office']
${MY_+categories_housekeepng_link}  //div[@id='categories']//a[@href='https://iprice.my/housekeeping/']//span[text()='Housekeeping']
${MY_+categories_kitchen_dining_link}  //div[@id='categories']//a[@href='https://iprice.my/kitchen-dining/']//span[text()='Kitchen & Dining']
${MY_+categories_lighting_link}  //div[@id='categories']//a[@href='https://iprice.my/lighting/']//span[text()='Lighting']
${MY_+categories_living_room_link}  //div[@id='categories']//a[@href='https://iprice.my/living-room/']//span[text()='Living Room']
${MY_+categories_outdoor_garden_link}  //div[@id='categories']//a[@href='https://iprice.my/outdoor-garden/']//span[text()='Outdoor & Garden']
${MY_+categories_pets_suplies_link}  //div[@id='categories']//a[@href='https://iprice.my/pets-supplies/']//span[text()='Pets Supplies']
${MY_+categories_security_link}  //div[@id='categories']//a[@href='https://iprice.my/security/']//span[text()='Security']
${MY_+categories_stationery_link}  //div[@id='categories']//a[@href='https://iprice.my/stationery/']//span[text()='Stationery']
${MY_+categories_gadgets_link}  //div[@id='categories']//a[@href='https://iprice.my/gadgets/']//span[text()='Gadgets']
# ${MY_+categories_other_sports_link}  //div[@id='categories']//a[@href='https://iprice.my/other-sports/']//span[text()='Other Sports']
${MY_+categories_upcoming_products_link}  //div[@id='categories']//a[@href='https://iprice.my/upcoming-products/']//span[text()='Upcoming Products']

${MY_search_compare_save_header}  //h1[contains(@id,'slogan') and text()='Search, Compare & Save']
${MY_search_compare_save_electronic_gaming_box}  //div[@id='hp-electronics']
${MY_search_compare_save_electronic_gaming_box_computing}  //div[@id='hp-parent']//span[text()='Computing']
${MY_search_compare_save_fashion_beauty_box}  //div[@id='hp-fashion']
${MY_search_compare_save_fashion_beauty_box_clothing}  //div[@id='hp-parent']//span[text()='Clothing']
${MY_search_compare_save_coupons_offers_box}  //div[@id='hp-coupon']
${MY_search_compare_save_coupons_offers_box_electronics}  //div[@id='hp-parent']//span[text()='Electronics']

${MY_product_images}  //img[contains(@class,'lazy product-img')]

${MY_coupon_page_title}  Get Exclusive Coupons, Discount Codes & Vouchers in 2017 | iPrice Malaysia
${MY_coupon_see_all_store_link}  //div[@id='coupon-overview']//a[text()='See All Stores >']
${MY_coupon_stores_title}  Online Shop & Sales, Buy Fashion & Electronics Online at iprice Malaysia

${COOD_says_url}  http://coupon.says.com/
${COOD_says_title}  Discount Codes, Coupons & Promos | coupon.says.com
${COOD_says_navbar_header_logo}  //div[@class='container']//a[contains(@href,'http://says.com') and text()='SAYS']
${COOD_says_navbar_header_news}  //div[@class='container']//a[contains(@href,'http://says.com/my/news') and text()='NEWS']
${COOD_says_navbar_header_fun}  //div[@class='container']//a[contains(@href,'http://says.com/my/fun') and text()='FUN']
${COOD_says_navbar_header_lifestyle}  //div[@class='container']//a[contains(@href,'http://says.com/my/lifestyle') and text()='LIFESTYLE']
${COOD_says_navbar_header_entertainment}  //div[@class='container']//a[contains(@href,'http://says.com/my/entertainment') and text()='ENTERTAINMENT']
${COOD_says_navbar_header_sport}  //div[@class='container']//a[contains(@href,'http://says.com/my/sports') and text()='SPORTS']
${COOD_says_navbar_header_tech}  //div[@class='container']//a[contains(@href,'http://says.com/my/tech') and text()='TECH']
${COOD_says_navbar_header_imho}  //div[@class='container']//a[contains(@href,'http://says.com/my/imho') and text()='IMHO']
${COOD_says_navbar_header_seismik}  //div[@class='container']//a[contains(@href,'http://says.com/my/seismik') and text()='SEISMIK']
${COOD_says_navbar_header_coupons}  //div[@class='container']//a[contains(@href,'http://coupon.says.com/') and text()='COUPONS']
${COOD_says_banner}  //div[@id='coupon-overview']//div[@class='banner']
${COOD_says_categories_header}  //div[@id='coupon-overview']//span[text()='Categories']
${COOD_says_top_coupons_header}  //div[@id='coupon-overview']//span[text()=' Top Coupons ']
${COOD_says_recent_coupons_header}  //div[@id='coupon-overview']//span[text()=' Recent Coupons ']
${COOD_says_featured_stores_header}  //div[@id='coupon-overview']//span[text()='Featured Stores']
${COOD_says_content_header}  //div[@id='coupon-overview']//strong[text()='Online Shopping – a phenomenal living life style through the decade']
${COOD_says_footer_logo}  //div[@class='container']//div[@class='logo-xs']

${COOD_rappler_en_url}  http://coupons.rappler.com/
${COOD_rappler_en_title}  Promo codes, Coupons & Discount codes | Rappler.com
${COOD_rappler_en_navbar_header_logo}  //div[@class='menu-trigger nav-full']//img[@class='thinglinkFiltered']
${COOD_rappler_en_navbar_header_ph}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/') and text()='Philippines']
${COOD_rappler_en_navbar_header_id}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/indonesia/') and text()='Indonesia']
${COOD_rappler_en_header}  //div[@id='coupon-overview']//h1[text()=' Coupons on Rappler.com ']
${COOD_rappler_en_featured_coupons_header}  //div[@id='coupon-overview']//h2[text()='Featured Coupons']
${COOD_rappler_en_categories_header}  //div[@id='coupon-overview']//h1[text()='Categories']
${COOD_rappler_en_popular_coupons_header}  //div[@id='coupon-overview']//h1[text()='Popular Coupons']
${COOD_rappler_en_latest_coupons_header}  //div[@id='coupon-overview']//h1[text()='Latest Coupons']
${COOD_rappler_en_content_area}  //div[@id='coupon-overview']//div[@class='content-text']
${COOD_rappler_en_footer_area}  //div[@id='footer-wrapper']

${COOD_rappler_id_url}  http://kupon.rappler.com/
${COOD_rappler_id_title}  Promo Kode, Kupon, Diskon Kode, Sale & Voucher di Agustus 2017 | Rappler Indonesia
${COOD_rappler_id_navbar_header_logo}  //div[@class='menu-trigger nav-full']//img[@class='thinglinkFiltered']
${COOD_rappler_id_navbar_header_ph}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/') and text()='Philippines']
${COOD_rappler_id_navbar_header_id}  //div[@class='menu-trigger nav-full']//a[contains(@href,'http://www.rappler.com/indonesia/') and text()='Indonesia']
${COOD_rappler_id_header}  //div[@id='coupon-overview']//h1[text()=' Beragam Kupon Pilihan di Rappler.com ']
${COOD_rappler_id_featured_coupons_header}  //div[@id='coupon-overview']//h2[text()='Beragam Kupon Pilihan']
${COOD_rappler_id_categories_header}  //div[@id='coupon-overview']//h1[text()='Kategori']
${COOD_rappler_id_popular_coupons_header}  //div[@id='coupon-overview']//h1[text()='Kupon Terpopuler']
${COOD_rappler_id_latest_coupons_header}  //div[@id='coupon-overview']//h1[text()='Kupon Terbaru']
${COOD_rappler_id_content_area}  //div[@id='coupon-overview']//div[@class='content-text']
${COOD_rappler_id_footer_area}  //div[@id='footer-wrapper']

${MY_sort_by_text}  //div[@id='sort']//div[contains(text(),'Sort by')]
${MY_sort_by_button}  //div[@id='sort']//button[@class='sorting-dropdown list-trigger']
${MY_sort_by_down_arrow}  //div[@id='sort']//i[@class='icon icon-drop-gray']
${MY_sort_by_popularity_text}  //div[@id='sort']//a[text()='Popularity']
${MY_sort_by_relevance_text}  //div[@id='sort']//a[text()='Relevance']
${MY_sort_by_ascending_text}  //div[@id='sort']//a[text()='Price (ascending)']
${MY_sort_by_descending_text}  //div[@id='sort']//a[text()='Price (descending)']
${MY_sort_by_name_text}  //div[@id='sort']//a[text()='Name']

${MY_filter_price_header}  //div[@class='list-item price']//h2[text()='Price']
${MY_filter_price_min_price_box}  //div[@class='list-item price']//input[@name='price_min']
${MY_filter_price_max_price_box}  //div[@class='list-item price']//input[@name='price_max']
${MY_filter_price_slider}  //div[@class='list-item price']//div[contains(@class,'ui-slider-horizontal')]

${MY_footer_international_header}  //div[@id='international']//div[text()='International']
${MY_footer_international_singapore_link}  //div[@id='international']//a[contains(@href,'https://iprice.sg/') and normalize-space(text()='Singapore')]
${MY_footer_international_indonesia_link}  //div[@id='international']//a[contains(@href,'https://iprice.co.id/') and normalize-space(text()='Indonesia')]
${MY_footer_international_philippines_link}  //div[@id='international']//a[contains(@href,'https://iprice.ph/') and normalize-space(text()='Philippines')]
${MY_footer_international_hong_kong_link}  //div[@id='international']//a[contains(@href,'https://iprice.hk/') and normalize-space(text()='Hong Kong')]
${MY_footer_international_thailand_link}  //div[@id='international']//a[contains(@href,'https://ipricethailand.com/') and normalize-space(text()='Thailand')]
${MY_footer_international_vietnam_link}  //div[@id='international']//a[contains(@href,'https://iprice.vn/') and normalize-space(text()='Vietnam')]
${MY_footer_ipricegroup_header}  //div[@id='ipricegroup']//div[text()='iPrice group']
${MY_footer_ipricegroup_about_us_link}  //div[@id='ipricegroup']//a[contains(@href,'http://ipricegroup.com/') and normalize-space(text()='About Us')]
${MY_footer_ipricegroup_trends_link}  //div[@id='ipricegroup']//a[contains(@href,'https://iprice.my/trends/') and normalize-space(text()='Trends')]
${MY_footer_ipricegroup_contact_us_link}  //div[@id='ipricegroup']//a[contains(@href,'http://ipricegroup.com/contact.html') and normalize-space(text()='Contact Us')]
${MY_footer_ipricegroup_carreers_link}  //div[@id='ipricegroup']//a[contains(@href,'http://ipricegroup.com/career.html') and normalize-space(text()='Careers')]
${MY_footer_ipricegroup_partners_link}  //div[@id='ipricegroup']//a[contains(@href,'http://ipricegroup.com/partner.html') and normalize-space(text()='Partners')]
${MY_footer_ipricegroup_privacy_policy_link}  //div[@id='ipricegroup']//a[contains(@href,'https://iprice.my/privacy-policy/') and normalize-space(text()='Privacy Policy')]
${MY_footer_ipricegroup_terms_of_use_link}  //div[@id='ipricegroup']//a[contains(@href,'https://iprice.my/terms-of-use/') and normalize-space(text()='Terms of Use')]
${MY_footer_ipricegroup_iema_link}  //div[@id='ipricegroup']//a[contains(@href,'https://iprice.my/iema/2016/') and normalize-space(text()='iEMA')]

${MY_footer_social_header}  //div[@id='social']//div[text()='Social']
${MY_footer_social_facebook_link}  //div[@id='social']//a[contains(@href,'https://www.facebook.com/ipriceMalaysia') and normalize-space(text()='Facebook')]
${MY_footer_social_pinterest_link}  //div[@id='social']//a[contains(@href,'https://www.pinterest.com/ipricemy') and normalize-space(text()='Pinterest')]
${MY_footer_social_twitter_link}  //div[@id='social']//a[contains(@href,'https://twitter.com/iPriceMY') and normalize-space(text()='Twitter')]
${MY_footer_social_google+_link}  //div[@id='social']//a[contains(@href,'http://plus.google.com/+Ipricegroup/about') and normalize-space(text()='Google+')]

${MY_product_list}  //section[@class='product-list']//a[@class='product-unit hover-popup product cursor-pointer']
