*** Settings ***
Documentation    This file will only store variables for TH.

*** Variables ***

${TH_homeURL}  https://ipricethailand.com/?nocache=1
${TH_homeTitle}  ipriceThailand - ค้นหา เช็กราคา ที่เดียวครบสุดคุ้ม
${TH_header_logo}  //div[contains(@id,'logo') and @class='th']
${TH_header_logo_link}  //div[@id='logo']//a[@href='https://ipricethailand.com/']
${TH_header_search_input}  //div[@id='search']//input[@placeholder='ค้นหาสินค้า,คูปองหรือแบรนด์...']
${TH_header_search_icon}  //div[@id='search']//i[@class='icon icon-search-blue']
${TH_header_popular_searches_text}  //div[@id='popular-searches']//li[normalize-space(text())='\u200bคำค้นหายอดนิยม:']
${TH_header_coupon_logo_link}  //div[@id='news-button']//a[@href='https://ipricethailand.com/coupons/']
${TH_header_coupon_text}  //div[@id='news-button']//*[(contains(text(),'คูปอง &') and (normalize-space(text()='ข้อเสนอ')))]
${TH_header_categories_clothing_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองแตงกาย/']//span[text()='เครื่องแต่งกาย']
${TH_header_categories_clothing_men}  //div[@id='menu']//a[contains(@href,'https://ipricethailand.com/เครองแตงกาย/ผชาย/') and text()='ผู้ชาย']
${TH_header_categories_clothing_women}  //div[@id='menu']//a[contains(@href,'https://ipricethailand.com/เครองแตงกาย/ผหญง/') and text()='ผู้หญิง']
${TH_header_categories_shoes_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/รองเทา/']//span[text()='รองเท้า']
${TH_header_categories_shoes_men}  //div[@id='menu']//a[contains(@href,'https://ipricethailand.com/รองเทา/ผชาย/') and text()='ผู้ชาย']
${TH_header_categories_shoes_women}  //div[@id='menu']//a[contains(@href,'https://ipricethailand.com/รองเทา/ผหญง/') and text()='ผู้หญิง']
${TH_header_categories_bags_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/กระเปา/']//span[text()='กระเป๋า']
${TH_header_categories_watches_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/นาฬกาขอมอ/']//span[text()='นาฬิกาข้อมือ']
${TH_header_categories_jewellery_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองประดบ/']//span[text()='เครื่องประดับ']
${TH_header_categories_computing_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณคอมพวเตอร/']//span[text()='อุปกรณ์คอมพิวเตอร์']
${TH_header_categories_phones_tablets_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/โทรศพทและแทบเลต/']//span[text()='โทรศัพท์และแท็บเล็ต']
${TH_header_categories_gaming_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองเลนเกมส/']//span[text()='เครื่องเล่นเกมส์']
${TH_header_categories_camera_photo_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/กลองถายรปและรปภาพ/']//span[text()='กล้องถ่ายรูปและรูปภาพ']
${TH_header_categories_tv_video_dvd_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ทว-วดโอ-และดวด/']//span[text()='ทีวี วีดีโอ และดีวีดี']
${TH_header_categories_appliances_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองใชไฟฟา/']//span[text()='เครื่องใช้ไฟฟ้า']
${TH_header_categories_automotive_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ยานยนต/']//span[text()='ยานยนต์']
${TH_header_categories_+_categories_link}  //div[@id='menu']//a[contains(@href,'https://ipricethailand.com/categories/') and text()='+ ประเภท']
${TH_header_categories_hobbies_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/งานอดเรก/']//span[text()='งานอดิเรก']
${TH_header_categories_audio_hifi_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองเสยงและ-hi-fi/']//span[text()='เครื่องเสียงและ Hi Fi']
${TH_header_categories_action_sport_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/กฬาเอกซตรม/']//span[text()='กีฬาเอ็กซ์ตรีม']
${TH_header_categories_adventure_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/การผจญภย/']//span[text()='การผจญภัย']
${TH_header_categories_baby_clothing_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองแตงกายสำหรบเดกทารก/']//span[text()='เครื่องแต่งกายสำหรับเด็กทารก']
${TH_header_categories_baby_gear_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณการเดนทางสำหรบเดก/']//span[text()='อุปกรณ์การเดินทางสำหรับเด็ก']
${TH_header_categories_bath_body_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑดแลและทำความสะอาดผวกาย/']//span[text()='ผลิตภัณฑ์ดูแลและทำความสะอาดผิวกาย']
${TH_header_categories_dental_care_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑดแลชองปาก/']//span[text()='ผลิตภัณฑ์ดูแลช่องปาก']
${TH_header_categories_diapering_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณสำหรบการเปลยนผาออม/']//span[text()='อุปกรณ์สำหรับการเปลี่ยนผ้าอ้อม']
${TH_header_categories_eyecare_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑสำหรบดวงตา/']//span[text()='ผลิตภัณฑ์สำหรับดวงตา']
${TH_header_categories_feeding_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อาหาร-นมและอปกรณอนๆ/']//span[text()='อาหาร นมและอุปกรณ์อื่นๆ']
${TH_header_categories_food_supplements_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อาหารเสรมสำหรบออกกำลงกาย/']//span[text()='อาหารเสริมสำหรับออกกำลังกาย']
${TH_header_categories_gifts_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ของขวญ/']//span[text()='ของขวัญ']
${TH_header_categories_gym_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ฟตเนส/']//span[text()='ฟิตเนส']
${TH_header_categories_hair_care_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑดแลเสนผม/']//span[text()='ผลิตภัณฑ์ดูแลเส้นผม']
${TH_header_categories_health_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/สขภาพ/']//span[text()='สุขภาพ']
${TH_header_categories_kids_clothing_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองแตงกายสำหรบเดก/']//span[text()='เครื่องแต่งกายสำหรับเด็ก']
${TH_header_categories_makeup_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองสำอาง/']//span[text()='เครื่องสำอาง']
${TH_header_categories_maternity_care_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑสำหรบคณแม/']//span[text()='ผลิตภัณฑ์สำหรับคุณแม่']
${TH_header_categories_medical_supplies_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เวชภณฑ/']//span[text()='เวชภัณฑ์']
${TH_header_categories_nursery_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เนอสเซอร/']//span[text()='เนอสเซอรี่']
${TH_header_categories_perfeum_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/นำหอม/']//span[text()='น้ำหอม']
${TH_header_categories_racquet_sports_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/กฬาประเภทแรกเกต/']//span[text()='กีฬาประเภทแร็กเกต']
${TH_header_categories_shaving_supplies_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑกำจดขน/']//span[text()='ผลิตภัณฑ์กำจัดขน']
${TH_header_categories_skin_care_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑดแลผว/']//span[text()='ผลิตภัณฑ์ดูแลผิว']
${TH_header_categories_supplements_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อาหารเสรม/']//span[text()='อาหารเสริม']
${TH_header_categories_team_sports_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/กฬาประเภททม/']//span[text()='กีฬาประเภททีม']
${TH_header_categories_toys_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ของเลน/']//span[text()='ของเล่น']
${TH_header_categories_water_sports_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/กฬาทางนำ/']//span[text()='กีฬาทางน้ำ']
${TH_header_categories_groceries_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ของชำ/']//span[text()='ของชำ']
${TH_header_categories_ear_care_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑดแลสขภาพห/']//span[text()='ผลิตภัณฑ์ดูแลสุขภาพหู']
${TH_header_categories_bathroom_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/หองนำ/']//span[text()='ห้องน้ำ']
${TH_header_categories_bedroom_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/หองนอน/']//span[text()='ห้องนอน']
${TH_header_categories_hallway_entry_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/หองโถงและทางเขา/']//span[text()='ห้องโถงและทางเข้า']
${TH_header_categories_home_decor_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ของตกแตงบาน/']//span[text()='ของตกแต่งบ้าน']
${TH_header_categories_home_improvement_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณดแลรกษาและซอมแซมบาน/']//span[text()='อุปกรณ์ดูแลรักษาและซ่อมแซมบ้าน']
${TH_header_categories_home_office_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณสำนกงาน/']//span[text()='อุปกรณ์สำนักงาน']
${TH_header_categories_housekeepng_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณทำความสะอาดบาน/']//span[text()='อุปกรณ์ทำความสะอาดบ้าน']
${TH_header_categories_kitchen_dining_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/หองครวและหองรบประทานอาหาร/']//span[text()='ห้องครัวและห้องรับประทานอาหาร']
${TH_header_categories_lighting_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ไฟ/']//span[text()='ไฟ']
${TH_header_categories_living_room_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/หองนงเลน/']//span[text()='ห้องนั่งเล่น']
${TH_header_categories_outdoor_garden_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณภายนอกและของแตงสวน/']//span[text()='อุปกรณ์ภายนอกและของแต่งสวน']
${TH_header_categories_pets_suplies_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/อปกรณสำหรบสตวเลยง/']//span[text()='อุปกรณ์สำหรับสัตว์เลี้ยง']
${TH_header_categories_security_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ความปลอดภย/']//span[text()='ความปลอดภัย']
${TH_header_categories_stationery_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/เครองเขยน/']//span[text()='เครื่องเขียน']
${TH_header_categories_gadgets_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/แกดเจต/']//span[text()='แก็ดเจ็ต']
${TH_header_categories_other_sports_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/กฬาอนๆ/']//span[text()='กีฬาอื่นๆ']
${TH_header_categories_upcoming_products_link}  //div[@id='menu']//a[@href='https://ipricethailand.com/ผลตภณฑมาใหม/']//span[text()='ผลิตภัณฑ์มาใหม่']

${TH_product_images}  //img[contains(@class,'lazy product-img')]

${TH_coupon_page_title}  แจก ดีล คูปอง รหัสส่วนลด บัตรส่วนลด โปรโมชั่น ของปี พ.ศ. 2560 ที่ iprice ประเทศไทย
${TH_coupon_see_all_store_link}  //div[@id='coupon-overview']//a[text()='ดูร้านค้าทั้งหมด >']
${TH_coupon_stores_title}  ร้านค้า | iprice ประเทศไทย
